### ISSUE TITLE
usr_uptime. lua issue with V 2.21 aswell 2.20

### ISSUE THREAD

**Issue by Tadies** [luadch/luadch#106]
hi.... now ill hope it's not my end.....
but i got a hughe load on error log that shows every second.....i had to disable this  script....
i never noticed this cause i use web version of airdc....
but i did fire up since long time aridc for weirdows then i saw it.......

`[2020-09-29 | 19:31:22] scripts.lua: script error: ././core/util.lua:229: bad argument #1 to 'pairs' (table expected, got nil) (listener: onTimer; script: 'usr_uptime.lua')`
the log file was over 13mb..... full of this error
this is what i saw on my last used working V2.20...
so i decided to get a new hubsoft up and running.......
guess what same stuff happens..

any had same trouble?
thank you.....

**Comment by perlaxe** [comment]
"table expected, got nil"
Check permissions of the file and have a look if it is readable, perhaps it got corrupted and not properly formatted now.

**Comment by Tadies** [comment]
Thank You perlaxe...
the problem has been solved  with help of anohter fine member..
and me was given anohter usr_uptime.lua ....
that one worked strait out of the box...
sidenote: i had to use also an new empty .tbl....
maybe the usr_uptime.lua  was not gaven to the new arm package??
anyway its solved now thanky!  rock on!
