### ISSUE TITLE
ACCINFO should show when a user is traffic/message blocked

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#107]
When viewing ACCINFO i can see if a user is online, but i can't see if the user is blocked. It would be really nice if it could show both traffic manager blocks and message blocks.

To keep the ACCINFO clean and easy to read it should only show the blocks when a user is blocked. When a user is not blocked there shouldn't be any information about it.

**Comment by pulsar-de** [comment]
Good idea, done. But if a user is not blocked (traffic/message) then it shows "NO".
