### ISSUE TITLE
hub.lua small changes

### ISSUE THREAD

**Issue by perlaxe** [luadch/luadch#108]
Hi, I made some change to hub.lua in my hub on migration from Flex.Please review and decide if it makes sense
-send error when a non registered user tries to join (as nick are case sensitive some valid user tries to log in with blabla user instead of BlaBla and ops need to be aware
-error on max pass tries
-output to error log including nickname

```1657a1658
>           out_error( "Nick: ", nick, " is not registered.")
1685a1687,1688
>                 out_error( "Nick: ", nick, " max password tries exceeded. Timeout in sec: ", sec)
>
1710a1714
>       local nick = user.nick( )
1722a1727,1728
>           out_error( "Nick: ", nick, " bad password.")
>
1887c1893
<         out_put( "hub.lua: function 'disconnect': remove user ", usersid, " ", ip, ":", port )
---
>         out_put( "hub.lua: function 'disconnect': remove user ", usernick , " SID: " ,usersid, " ", ip, ":", port )
```

**Comment by blasti** [comment]
Hi, can you do a pull request?

**Comment by perlaxe** [comment]
Hi. done, I edited with nano and used dos2unix some lua files, can try to add changes in DOS format if necessary.

**Comment by blasti** [comment]
Moved to #115
