### ISSUE TITLE
Serius security risk / Spoofed IPs

### ISSUE THREAD

**Issue by TheGargol** [luadch/luadch#110]
This hubsoft allowes users to spoof their IP and can therefor be used for DDos attacks on victims by spoofing the IP of the victim and making other clients connect to that IP and not the connected client.

When a client sends a INF containing I4 or I6 this should be verified against the IP the client is connecting to the hub from.
If they missmatch the hubsoft should either fix it or disconnect the client.

**Comment by blasti** [comment]
Are there any real world scenarios, where luadch hubs were involved in DDos? 
This would surprise me, as luadch is mostly used for small private hubs,
Anyway, to disconnect clients with mismatching IPs, add this to cfg.tbl:

kill_wrong_ips = true

This works in case of IPv4. The case of IPv6 shall be added later.

Warning: If you enable this setting, don't be surprised about complaining users, which rely on "spoofing" their IP. I remember such discussions took place years ago.
