### ISSUE TITLE
new listener for failed authentication events

### ISSUE THREAD

**Issue by perlaxe** [luadch/luadch#115]
Hi,

Please develop a new listener for scripts for failed authentication events like:

-nick is not registered
-bad password
-max password tries exceeded

Return values: nick, SID, IP

There could be more but these are the imporant ones right now to keep an eye on.

Thx.

**Comment by perlaxe** [comment]
I made something like this and inserted it into 3 places. It does the job with a script, but not sure if the 4th argument should be a text (which I chose for easy understanding) or just a number or st else.


```
scripts_firelistener( "onFailedauth", cid,nick,userip,"nonreg" ) 
scripts_firelistener( "onFailedauth", cid,nick,userip,"tries" ) 
scripts_firelistener( "onFailedauth", usercid,nick,userip,"badpass" )    -this also needs local nick = user.nick( )  and local userip = user.ip( ) or ""  in _verify
```

**Comment by pulsar-de** [comment]
added new listener "onFailedAuth"

the listener will be called on:

- _verify state

    - Invalid password

- _identify state

    - No CID/PID/nick found in INF
    - PID is invalid
    - CID is taken
    - NICK is taken
    - IP in INF does not match with real IP
    - Registered users only
    - Max bad password exceeded

here's a small example:

```lua
hub.setlistener( "onFailedAuth", {},
    function( nick, ip, reason )
        hub.broadcast( "[onFailedAuth]-> User: " .. nick .. " / IP: " .. ip .. " / Reason: " .. hub.escapefrom( reason ), hub.getbot() )
        return nil
    end
)
```

**Comment by pulsar-de** [comment]
As for the return of the ip, as soon as we have fully implemented the ipv6, the ipv4 / ipv6 could also be returned to the listener.
