### ISSUE TITLE
!hubinfo displaying wrong TLS version

### ISSUE THREAD

**Issue by 4C3T** [luadch/luadch#124]
I recently changed from 1.2 to 1.3, but got a report from a user that login shows (hubinfo) 1.2 being used, while the client says it's 1.3.

Did a quick look in the code, and both the scripts/cmd_hubinfo.lua and scripts/lang/cmd_hubinfo.lang.en only has a parameter %s, so it seem to get that info from the config file.

It's very possible that I've missed something, but I don't think so to be honest. Been going over the conf a few times, and I can't find anything that would explain this.
I suspect that any of the previously mentioned script files are used to include this in the motd at login.

**Comment by Sopor** [comment]
I think it is the same isse as https://github.com/luadch/luadch/issues/116
