### ISSUE TITLE
cmd_userinfo.lua - not correct reply for the command error

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#127]
After doing a `+userinfo sid XXXX` on a user i got this reply: `Target user has a higher level than you`, but after checking the user we have the same level (in this case 60). So the message should be change to something like this:
`Target user has a higher or same level as you`

https://github.com/luadch/luadch/blob/fd854299f7d8b68a63ed3ba1290df06091102dd4/scripts/lang/cmd_userinfo.lang.en#L6

**Comment by pulsar-de** [comment]
I can't reproduce this. If i use the userinfo command on a user with the same level then it works as it should.
the line in question is:
`if not ( user == target ) and ( ( permission[ level ] or 0 ) < target:level() ) then`
The less-than sign checks if the target level is higher.
