### ISSUE TITLE
Prevent post in main if space is before the command char [+!#]

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#129]
Since you remove the possibility to run command from the hubbot and only make it possible to run them from main it would be really nice if it was impossible to begin a command with space. What i mean is that it should detect that it is a command and show an error message instead of post it in main as a normal chat message.
`"Unknown command. Check leading spaces and syntax."`

**Comment by perlaxe** [comment]
I solved it by replacing :
`local command = utf_match( txt, "^[+!#](%a+)" )`

with: 
`local command = utf_match( txt, "^%s*[!#+](%a+)" )`

in etc_unknown_command.lua

Also changed the text: `local msg_denied = "Unknown command. Check leading spaces and syntax."`

**Comment by Sopor** [comment]
Thanks @perlaxe, your fix worked perfectly, but maybe two different error message would be better but i leave that to the devs :)

**Comment by Sopor** [comment]
If someone else want to prevent commands that start with a space to be sent to main you can replace your old `etc_unknown_command.lua` with [this file](https://github.com/luadch/luadch/files/6236179/etc_unknown_command.zip) and then do a `+reload`

**Comment by ManelGT1956** [comment]
Thanks!... Going to check it too...

**Comment by pulsar-de** [comment]
Thx @Sopor for the idea and @perlaxe for the code changes. Fixed.

**Comment by Sopor** [comment]
@pulsar-de There is a tiny issue with this fix. It will be visible in the history log

etc_chatlog_log.tbl:
```
return {

    { "2021-10-20 / 00:17:41", "[100]xxxxx", " +rules", },

}
```
The command begins with a space.
