### ISSUE TITLE
error loading module 'socket.core' from file '././lib/luasocket/socket/socket.so'

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#132]
I was trying to update to Luadch 2.21 on a Raspberry Pi, but i only get this error message:

```
error loading module 'socket.core' from file '././lib/luasocket/socket/socket.so':
	/lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ././lib/luasocket/socket/socket.so)
```

The installed version seems to be `libc6 | 2.24-11+deb9u4` and i won't get any newer version if i try to update and upgrade.

I did found this information:
`libc6 is a core library, most other libraries depend on it. It sounds like you're trying to install a binary that was compiled for a different distro than the one you're using. `

So, how do i fix this? Compile my own Luadch?

**Comment by pulsar-de** [comment]
Yes, you should compile a fresh luadch.

Heres a litte help to do this:

First of all, be sure that you are up2date:
`sudo apt-get update`
Maybe there is a newer version of your Raspbian OS out there, use:
`sudo apt-get upgrade`
To use Luadch you need the following software: "gcc" compiler, "openssl" and of course "git" to get luadch source, all should already be installed. If not use:
`sudo apt-get install gcc openssl git`
Now we can get luadch source, use:
`sudo git clone https://github.com/luadch/luadch.git`
Go into the new luadch folder and compile it, use:
`cd luadch`
then
`sudo ./compile`
After that you should have a new directory called "build_gcc", in this directory lays your fresh compiled luadch. don't forget to make certs...

After years without using my raspi, i try to build it by myself with a current version of raspbian os and it works without any problems. As client i have used "eiskaltdcpp".
