### ISSUE TITLE
usr_uptime.lua   Wrong time

### ISSUE THREAD

**Issue by Kungen123** [luadch/luadch#14]
The script must save the time more often than at logout. Maybe every 10min or so. 
Now you lose a lot of time every month.
Im online 24/7 here and here is my log in a hub.
I've lost several days already this month

Uptime Statistik von:  Kungen™

```
JAHR        MONAT       UPTIME
--------------------------------------------------------------------------------------------------------------------------------------------

2016    Januar      3 Tage, 0 Stunden, 19 Minuten, 18 Sekunden
2016    Februar     24 Tage, 17 Stunden, 37 Minuten, 2 Sekunden
2016    März       1 Tage, 16 Stunden, 29 Minuten, 36 Sekunden
2016    April       28 Tage, 17 Stunden, 56 Minuten, 46 Sekunden
2016    Mai     29 Tage, 6 Stunden, 38 Minuten, 17 Sekunden
2016    Juni        23 Tage, 22 Stunden, 51 Minuten, 42 Sekunden
2016    Juli        28 Tage, 6 Stunden, 57 Minuten, 26 Sekunden
2016    August      4 Tage, 5 Stunden, 13 Minuten, 23 Sekunden
```

**Comment by Sopor** [comment]
I have been online the whole month in the same hub and after i did a reconnect i now have been online: `2016    August      1 Tage, 8 Stunden, 52 Minuten, 14 Sekunden`. This can't be right and i see the same behavior in other hubs too.

**Comment by Kungen123** [comment]
yes i see it in other hubs too.

**Comment by Kungen123** [comment]
this script is not fixed yet ?
