### ISSUE TITLE
scripts.lua: script error: ././scripts/etc_chatlog.lua:272

### ISSUE THREAD

**Issue by Tracnare** [luadch/luadch#143]
Hello I encountered an error following the update of the server, the message appeared in the chat log and in the error.log file.
how to solve this error thanks for your help.

luadch: v2.22

`scripts.lua: script error: ././scripts/etc_chatlog.lua:272: wrong type: utf8 expected, got string (listener: onLogin; script: 'etc_chatlog.lua')`

**Comment by Sopor** [comment]
Convert the chatlog to UTF-8 and it should disappear.

**Comment by Ninja-FSE** [comment]
i also have this error message, looked in diffrent code programs like Visual Studio, Notepad++ and my etc_chatlog.lua is UTF-8.

running Luadch v2.22 RC4

**Comment by blasti** [comment]
> i also have this error message, looked in diffrent code programs like Visual Studio, Notepad++ and my etc_chatlog.lua is UTF-8.
> 

Open your `etc_chatlog.lua` in Notepad++, click in the menu on "Enocding" and convert it to UTF-8. Save the file.
Important: Do **not** use UTF-8-BOM.

**Comment by Ninja-FSE** [comment]
> > i also have this error message, looked in diffrent code programs like Visual Studio, Notepad++ and my etc_chatlog.lua is UTF-8.
> 
> Open your `etc_chatlog.lua` in Notepad++, click in the menu on "Enocding" and convert it to UTF-8. Save the file. Important: Do **not** use UTF-8-BOM.

This is not working, both Visual Studio and Notepad++ is showing UTF-8 and not UTF-8-Bom.

**Comment by Sopor** [comment]
@blasti So, it isn't the `etc_chatlog_log.tbl` that should be converted?

If i open the unmodified `etc_chatlog_log.tbl` after i compile Luadch it is in ANSI Latin 1

**Comment by Ninja-FSE** [comment]
i converted chat_log.tbl as well, didnt help

**Comment by Sopor** [comment]
@Eyeflow Did you shutdown Luadch before you converted it?

**Comment by Ninja-FSE** [comment]
@Sopor yes

**Comment by Sopor** [comment]
I get the same error message and i have tried to convert the log but it continues to show up at login.

If i view line for line with `+history show XX` i can view 16 lines but if i try 17 it won't show anything. I don't even get an error message.

I only get the error message when users login.

Line 17 has these chars `l|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅||` (it should look like a boom box i assume)

```
scripts.lua: script error: ././scripts/etc_chatlog.lua:269: wrong type: utf8 expected, got string (listener: onLogin; script: 'etc_chatlog.lua')
```

I'm running etc_chatlog.lua v1.3

I wonder if `+history reset_t_logs` will fix it permanently (yes, it is gone now after a history reset) or only temporary?

There must be another solution to fix this?

**Comment by blasti** [comment]
See also #158 and https://github.com/luadch/luadch/commit/8aad5d34b967765d5b4860f3668b983eca1b5535
