### ISSUE TITLE
etc_msgmanager.lua does not block MC messages

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#144]
```
    etc_msgmanager_permission_main = {  -- who is allowed to write main messages? (array of boolean)

        [ 0 ] = false,  -- unreg
```

Users are still allowed to write MC messages.

**Comment by Sopor** [comment]
It would help the developers if you also write what version of Luadch you are running.

**Comment by Tantrix** [comment]
Ah, yes, sorry.

2.22 Release

**Comment by Sopor** [comment]
I can confirm that main messages will not be blocked.

It seems that i can send PM even if that is set to false too, but maybe it won't affect PM's to OP's?

Tested on 2.23 RC9

```
+msgmanager showsettings

=== MESSAGE MANAGER =====================================

   Script is active:  true

   Blocked MAIN levels:

	UNREG

   Blocked PM levels:

	UNREG

===================================== MESSAGE MANAGER ===
```

**Comment by Tantrix** [comment]
> It seems that i can send PM even if that is set to false too

I cant confirm that.

```
    etc_msgmanager_permission_pm = {  -- who is allowed to write pm messages? (array of boolean)

        [ 0 ] = false,  -- unreg
```

`<Luadch> You are not allowed to write private messages.`

**Comment by Tantrix** [comment]
Yepp, bugged totally. Cant even block MC when it's allowed.

```
    etc_msgmanager_permission_main = {  -- who is allowed to write main messages? (array of boolean)

        [ 0 ] = true,  -- unreg
```
and
```
    etc_msgmanager_permission_pm = {  -- who is allowed to write pm messages? (array of boolean)

        [ 0 ] = false,  -- unreg
```

Then for zero level user:

>  <Luadch> [command] +msgmanager block**main** skupino
>  <Luadch> This user is already blocked.
>  <Luadch> [command] +msgmanager block**pm** skupino
>  <Luadch> This user is already blocked.
>  <Luadch> [command] +msgmanager unblock skupino
>  <Luadch> User not found.

**Comment by Sopor** [comment]
@Tantrix I suggest you to run `2.23 RC9` instead of 2.22 that has a lot of small bugs.

**Comment by Tantrix** [comment]
@Sopor Too late, Babylon is already running the latest release version.
However, I would be thankful for the quick fixes.

**Comment by pulsar-de** [comment]
> @Sopor Too late, Babylon is already running the latest release version. However, I would be thankful for the quick fixes.

quick fix:

 replace these files:
- "scripts/etc_msgmanager.lua"
- "scripts/lang/etc_msgmanager.lang.de"
- "scripts/lang/etc_msgmanager.lang.en"
