### ISSUE TITLE
min/max_nickname_length

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#145]
_min/max_nickname_length_ parameters seem to be not functional.

I.e. when 

`max_nickname_length = 32`

user **TEBAGINPIZDAMATIIDEOPTORISIJUMATATE** is able to connect.

2.22 Release.

**Comment by Sopor** [comment]
I assume it will not block already existing accounts. If `max_nickname_length` is set to 32, you will not be able to create an account that has more than 32 chars.

**Comment by Tantrix** [comment]
Oh? My goal was to limit regular users connecting, not just new accounts...
