### ISSUE TITLE
Some etc_trafficmanager.lua errors

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#146]
> - [2021-12-10 | 03:28:10] scripts.lua: script error: ././scripts/etc_trafficmanager.lua:808: wrong type: utf8 expected, got string (listener: onStart; script: 'etc_trafficmanager.lua')
> - [2021-12-10 | 03:30:10] scripts.lua: script error: ././scripts/etc_trafficmanager.lua:853: wrong type: utf8 expected, got string (listener: onConnect; script: 'etc_trafficmanager.lua')

Both errors were spotted during the initial hub configuration when playing with description prefixes and traffic manager scripts.

Errors appeared when the client with Russian chars in its description logged in. Its [BLOCKED] prefix was removed.

Not sure I can reproduce that, sorry.

2.22

**Comment by blasti** [comment]
Probably a problem in `format_description` with multiple byte utf-8 codepoints in the description of the user:

```lua
 local desc_part1 = desc:sub( 1, #desc_tag )
```

If `desc` contains multibytes, `desc:sub( 1, #desc_tag )` can screw it up. You end up with an invalid utf-8 string, which causes your error message. Solution: Use `utf8.sub` of a proper utf-8 lib, or rewrite the code in a safe way.

**Comment by pulsar-de** [comment]
Tried to reproduce it. In my tests i used a mixture of normal and 2-byte utf8 characters:

`"AݔAé ҈ ڴ߷ ߰fЊ۩Ћ؄ѬbÜصӕЌЍk֍Жc߾۞ѾФöЩҸЮäܮжфы"`

I used this string as a description tag as well as a blocked flag, unfortunately i could not reproduce the error. It would be great if you could post me some of the error-triggering characters so i can reproduce and fix the error.

**Comment by Tantrix** [comment]
Trying to reproduce.

I should ask: how to enable [BLOCKED] prefix in the nickname, not the description (or both)?

Why I'm asking: AFAIR when I spotted the bug that prefix was removed from the nickname (not sure about description).

**Comment by pulsar-de** [comment]
The trafficmanager does not change nick tags, only descriptions.

**Comment by Tantrix** [comment]
Oh, there is a new release, will run my tests there.

**Comment by Tantrix** [comment]
> The trafficmanager does not change nick tags

Hm, and what script does it actually?

**Comment by pulsar-de** [comment]
Any news on the problem?

**Comment by Tantrix** [comment]
Nope, none.

**Comment by pulsar-de** [comment]
Ok, thx.
