### ISSUE TITLE
usr_hubs.lua script misses redirect option

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#147]
Similar to 'slots' and 'share' scripts.

**Comment by blasti** [comment]
As Luadch is mostly running private hubs, redirection is not that important.

**Comment by Tantrix** [comment]
> Luadch is mostly running private hubs

That's why there is no need in users connected 100, 200, 300 or more hubs.

**Comment by pulsar-de** [comment]
Added redirect functionality. -> https://github.com/luadch/luadch/commit/73e1c9c7617fdf6dc9dc34b094acda86e20f6b58
