### ISSUE TITLE
Default hub(s) limit?

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#149]
The TE hublist says: Hub limit: 300

usr_hubs.lua is disabled.

How to remove the hub limit completely?

**Comment by Tantrix** [comment]
> <FlylinkDC++ 600.22859-x64,M:P-,H:295/0/12,S:15>

Aha, seems like that limitation is not in use, it's just a number sent to hublist.

**Comment by blasti** [comment]
Issue solved?

**Comment by Tantrix** [comment]
Not really.

Here you are: https://www.te-home.net/?do=hublist&id=5382

Not the hub of mine, but the number is pretty the same.

Again, it seems to be default maxhubs number sent to hublist.

**Comment by pulsar-de** [comment]
It would be interesting to find out how exactly the "hublist" determines this "max hub". 

default cfg.tbl:

```lua
    --// usr_hubs.lua settings | this script checks the hub count of a user

    max_hubs = 100,  -- max hubs (integer)
    max_user_hubs = 100,  -- max normal hubs (public hubs) (integer)
    max_reg_hubs = 100,  -- max reg hubs (integer)
    max_op_hubs = 100,  -- max op hubs (integer)
```

maybe it's a simple addition of these variables: ```max_user_hubs + max_reg_hubs + max_op_hubs```

**Comment by RoLex** [comment]
> It would be interesting to find out how exactly the "hublist" determines this "max hub".

@ https://nmdc.sourceforge.io/NMDC.html#_hubinfo

LuaDCH provides that value in ``$HubINFO``.

**Comment by blasti** [comment]
Luadch is an ADC hub. The NMDC protocol does not apply here, but the ADC Pinger extension does:

https://adc.sourceforge.io/ADC-EXT.html#_ping_pinger_extension

**Comment by pulsar-de** [comment]
> https://adc.sourceforge.io/ADC-EXT.html#_ping_pinger_extension

Yes thats the answer.

hub.lua:
```lua
--// from line 403:

_pingsup = "" ..
    "ISUP ADBAS0 ADBASE ADTIGR ADKEYP ADOSNR " .. --> ADKEYP (keyprint)
    "ADPING ADUCM0 ADUCMD\nISID %s\nIINF " ..
    "NI%s APLUADCH VE%s DE%s HH%s WS%s NE%s OW%s " ..
    "UC%s MS%s XS%s ML%s XL%s XU%s XR%s XO%s MC%s UP%s HU1 HI1 CT32\n"

--// from line 1697:

                response = utf_format( _pingsup,
                    user.sid( ),
                    _cfg_hub_name,
                    adclib_escape( VERSION ),
                    _cfg_hub_description,
                    _cfg_hub_hostaddress,
                    _cfg_hub_website,
                    _cfg_hub_network,
                    _cfg_hub_owner,
                    tablesize( _normalstatesids ),
                    _cfg_min_share[ 0 ] or 0,
                    max_share,
                    _cfg_min_slots[ 0 ] or 1,
                    _cfg_max_slots[ 0 ] or 100,
                    _cfg_max_user_hubs,
                    _cfg_max_reg_hubs,
                    _cfg_max_op_hubs,
                    _cfg_max_users,
                    os_difftime( os_time( ), signal_get( "start" ) )
                )
```
The hublist client pings the hubs and thus gets the necessary information for the evaluation. So it should also be clear that the data obtained in this way is individual for each hub and not static.

**Comment by Tantrix** [comment]
https://www.te-home.net/?do=hublist&id=5492 - the test hub

Again, usr_hubs.lua is disabled.

> maybe it's a simple addition of these variables

Will see :P

**Comment by pulsar-de** [comment]
hub.lua:
```lua
--// from line 2099:
    _cfg_max_user_hubs = cfg_get "max_user_hubs"
    _cfg_max_reg_hubs = cfg_get "max_reg_hubs"
    _cfg_max_op_hubs = cfg_get "max_op_hubs"
```
It doesn't matter if usr_hubs.lua is disabled, the information is loaded from cfg.tbl . :P

**Comment by Tantrix** [comment]
> the information is loaded from cfg.tbl

Anyway hub shouldn't send to hublist information different from its real rules.

> maybe it's a simple addition of these variables: max_user_hubs + max_reg_hubs + max_op_hubs

Correct.

>     max_user_hubs = 1,  -- max normal hubs (public hubs) (integer)
>     max_reg_hubs = 2,  -- max reg hubs (integer)
>     max_op_hubs = 3,  -- max op hubs (integer)

gives 

> Hub limit | 6

**Comment by pulsar-de** [comment]
> Anyway hub shouldn't send to hublist information different from its real rules.

In accordance with the [ADC Extensions](https://adc.sourceforge.io/ADC-EXT.html#_ping_pinger_extension) rules (3.4. PING - Pinger extension) the hub sends additional informations to hublist pingers, **but:**

hub.lua
```lua
--// line 1694

if (not _cfg_reg_only) and adccmd:hasparam "ADPING" then

--// line 2089:

_cfg_reg_only = cfg_get "reg_only"
```
cfg.tbl:
```lua
--// line 35:

reg_only = true,  -- reg only hub (boolean)
```
**...the hub only does this when running in public mode**



I think that should really be the end of the topic now :)

**Comment by HadesDCH** [comment]
So for max hubs setting  -> adc hub soft should be sending  IINF to pinger with MU (integer)? along with the rest of info???
...
Never seen a single adc soft sending this - so i consider it unsupported in general.

**Comment by pulsar-de** [comment]
> So for max hubs setting -> adc hub soft should be sending IINF to pinger with MU (integer)? along with the rest of info???

Are you sure? what reference are you referring to?

[ADC Extensions](https://adc.sourceforge.io/ADC-EXT.html#_ping_pinger_extension) -> _MU  |  integer  |  Minimum hubs connected where clients can be users_

Unfortunately i can't find any flag related to "max hubs" setting...

**Comment by HadesDCH** [comment]
> > So for max hubs setting -> adc hub soft should be sending IINF to pinger with MU (integer)? along with the rest of info???
> 
> Are you sure? what reference are you referring to?
> 
> [ADC Extensions](https://adc.sourceforge.io/ADC-EXT.html#_ping_pinger_extension) -> _MU | integer | Minimum hubs connected where clients can be users_
> 
> Unfortunately i can't find any flag related to "max hubs" setting...

You are right. Minimum. 
How about XU then?  <html>
<body>


XU | integer | Maximum hubs connected where clients can be users
-- | -- | --



</body>
</html>

I'm confused on this myself.

**Comment by Tantrix** [comment]
Wow wow, wait a minute, there is a couple of problems actually.

1) That's not right to use script parameter as a basic hub parameter because in case of disabled script (my case above) a hublist gets an irrelevant information.

2) It seems like there is no 'max_hubs_total' or 'hub limit' for ADC pinger INF at all. But for sure that number should not be presented as a summa of restrictions.

**Comment by blasti** [comment]
> > the information is loaded from cfg.tbl
> 
> Anyway hub shouldn't send to hublist information different from its real rules.
> 

Then just don't disable `usr_hubs.lua`, which will ensure, that the hub rules are carried out.
To summarize:

1) If in public mode, Luadch will correctly send information according to the ADC PING extension.
2) There are 3 different hub limits. How the hublist software interprets and displays it, is not Luadch's concern.
3) If in reg-only mode, Luadch will not reply to hublists.
4) Don't disable `usr_hubs.lua`

**Comment by blasti** [comment]
> Wow wow, wait a minute, there is a couple of problems actually.
> 
> 1. That's not right to use script parameter as a basic hub parameter because in case of disabled script (my case above) a hublist gets an irrelevant information.

You can always shoot yourself in the foot, if you want to. Luadch will not prevent this.
I admit, that there is no clear distinction between core/scripts parameters in the cfg.tbl anymore.
This is something I actually think about.

> 2. It seems like there is no 'max_hubs_total' or 'hub limit' for ADC pinger INF at all. But for sure that number should not be presented as a summa of restrictions.

Not Luadch's concern. This is something the ADC protocol needs to address. 

> 3. There is a possibility (and actually a real need from a hub admin point of view) to add an internal 'total hubs client connected' counter restriction as made i.e. in uHub: https://github.com/janvidar/uhub/blob/35d8088b447527f56609b85b444bd0b10cd67b5c/src/core/inf.c#L528

The total internal hubs of Luadch can be set in `cfg.tbl` with entry `max_hubs`

**Comment by Tantrix** [comment]
I see now, thanks.

Seems to be hublist problem, not luadch.

**Comment by RoLex** [comment]
Oh, indeed it is an ADC hub. I was too fast to answer the question, because in NMDC there is only one parameter - total number of hubs, regardless the (N)ormal/(U)ser, (O)perator or (R)egistered status.

I guess this becomes an issue due to same "display" of both NMDC and ADC hubs on my hublist. Since ADC states different hub limit numbers, in next version I will make sure to display them different for ADC hubs. Thanks for report! :)
