### ISSUE TITLE
CCPM from allowed level to lower levels will not work

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#15]
If you have disabled CCPM for level 20 and level 100 is allowed to use it the user with level 100 can't connect with CCPM, but the user with level 20 can if they try to connect to each other.
If two different levels use PM the user with the highest level should be prioritised, so in this case both user should be able to use CCPM to each other.

**Comment by blasti** [comment]
i cannot confirm, that low level users without CCPM flag can connect to user with CCPM flag. in my tests, the connection attempt just got stuck, there was no message of success. even if this is possible, i would not consider it as a bug. the only purpose of the script is to prevent low level user to use CCPM, to give the hub the possibility to spy on the private messages users. 

1) i really dont like this
2) if you nevertheless want to spy your users, then block CCPM for everybody. this would be fair

btw is thre somewhere an official specification of CCPM?

**Comment by Sopor** [comment]
Of course this is a bug. If you prevent low level users from using why can i then connect to high level users? You have to test it with two different users with different IP addresses. I believe when the user gets blocked it will block both users because they use the same IP address.

**Comment by Kungen123** [comment]
yes i think its a bug like Sopor. and i know that its a hole lot of work to fix it

**Comment by blasti** [comment]
fixed with ccpm_blocker2.0

> ```
>         - This script controls the CCPM - Client to Client Private Message feature, but this time more clever.
>         - It works like this: all users get their CCPM flag removed by default.
>         - If two users are above op_level, and support both CCPM, and message each other, then CCPM flags will be send to both.
>         - After that, CCPM can be established. So a user just needs to check, whether CCPM is available, after the first sent message.
> ```
