### ISSUE TITLE
How do I create a hub that users can register alone?

### ISSUE THREAD

**Issue by Havokdan** [luadch/luadch#153]
How do I create a hub that users can register alone? As in most NMDC hubs, I would like to know which options I should move to look like them at that point.

**Comment by mdPlusPlus** [comment]
I'm new to Luadch, but I think you need to change `reg_only = true,` to `reg_only = false,` in `cfg/cfg.tbl`.

**Comment by Havokdan** [comment]
> I'm new to Luadch, but I think you need to change `reg_only = true,` to `reg_only = false,` in `cfg/cfg.tbl`.

Yes, but that does not allow it to register.

**Comment by Sopor** [comment]
When you change `reg_only` to `false` it will only be a public hub. The user can't register himself. An OP need to do that.

I haven't seen any command for it, so i think you need to do a feature request for it @Havokdan if you want it.

**Comment by blasti** [comment]
One can write a script to allow self registering, please go ahead.

**Comment by pulsar-de** [comment]
There is already an old script for this: [cmd_regme.lua](https://github.com/luadch/luadch/blob/master/examples/etc/other_available_scripts/cmd_regme.lua)

However, I can only advise against giving users the opportunity to register themselves.
