### ISSUE TITLE
[2.22-Linux-x64] make_cert.sh has the wrong line endings

### ISSUE THREAD

**Issue by mdPlusPlus** [luadch/luadch#154]
```
$ ./make_cert.sh
-bash: ./make_cert.sh: /usr/bin/sh^M: bad interpreter: No such file or directory
```
To fix:
```
$ dos2unix make_cert.sh
$ ./make_cert.sh
Signature ok
subject=CN = xxx
Getting CA Private Key
```

The bash files (*.sh) are also not executable by default (`chmod +x *.sh)`, but I'm not sure whether that might be a limitation by `tar`.

**Comment by mdPlusPlus** [comment]
This seems to be an issue only in the release tarball, not in the actual code itself. Does someone manually create these tarballs?

**Comment by pulsar-de** [comment]
- changed: "certs/make_cert.sh"
        - changed to unix line endings "LF"

    - changed: "certs/make_keyprint.sh"
        - changed to unix line endings "LF"

    - changed: "certs/show_certinfo.sh"
        - changed to unix line endings "LF"

thx.
