### ISSUE TITLE
Non-Ascii two byte charcter В in scripts/cmd_gag.lua

### ISSUE THREAD

**Issue by mdPlusPlus** [luadch/luadch#156]
See  
https://github.com/luadch/luadch/blob/78fb01dcf766e2528c3b24442b2bc04e588d69cf/scripts/cmd_gag.lua#L66  
and  
https://github.com/luadch/luadch/blob/78fb01dcf766e2528c3b24442b2bc04e588d69cf/scripts/cmd_gag.lua#L71

The letter `В` in `"*Вumf* "` is a non-ascii two byte char which translates to `208 146` while a normal ascii single byte `B` translates to `066`. It is the only non-ascii char in `char_tbl` so I don't think this is intentional.

Can anyone explain to me why this non-ascii char has been used here? Should it be replaced by a ascii B to not cause any issues with client encoding?

**Comment by Sopor** [comment]
![image](https://user-images.githubusercontent.com/5789283/156894880-7c51702f-010b-45e0-bf8a-80a251aa3df5.png)

**Comment by blasti** [comment]
As long as it is utf-8 encoded, everything is fine. Anyway, I replaced non-ASCII chars in that script (see 71cb24d)
