### ISSUE TITLE
pm2offliners - attempt to get length of field '?'

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#16]
I'm not a Lua expert but i believe this error (loop, because it was repeated every second) happens if you login but you get kicked out for another reason. Maybe you have too many slots open or you are in too many hubs.
`scripts.lua: script error: ././scripts/cmd_pm2offliners.lua:237: attempt to get length of field '?' (a nil value) (listener: onTimer; script: 'cmd_pm2offliners.lua')`

**Comment by blasti** [comment]
should be fixed now. thanks for the report! found other nasty bugs too.

> ```
> cmd_pm2offliners.lua by pulsar
> ```

```
    Description: sends a PM to an offline User

    v0.7: by blastbeat
        - fixed error reported by sopor; if we use a delay here, we MUST CHECK whether upvalues did change in the meantime.
          users might be offline again, or delregged; the pm_tbl database might be cleaned;
          in the end it is a BAD idea to use a delay, makes things complicated, has zero benefits (-_-)
        - tried to clean up a bit, but not too much, who knows what breaks next
```
