### ISSUE TITLE
Wrong minshare send to hublist

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#164]
>     min_share = {  -- min share in GIGA BYTE (array of integer)
> 
>         [ 0 ] = 1,  -- unreg (default = 0 giga byte)

> IINF NILuadch\sTest\sHub APLUADCH VEv2.22 DE HHmoscow.hopto.org WShttps://luadch.github.io NEAdvanced\sDirect\sConnect OWTantrix UC3 **MS1** XS2.199023255552e+014 ML1 XL100 XU1 XR1 XO1 MC2008 UP24512 HU1 HI1 CT32

According to hub settings and https://adc.sourceforge.io/ADC-EXT.html#_ping_pinger_extension **MS1** should be **MS1048576**

**Comment by pulsar-de** [comment]
converted "_cfg_min_share" in "_pingsup" from gigabyte to byte  / thx Tantrix
