### ISSUE TITLE
Luadch binary not loading SSL lib

### ISSUE THREAD

**Issue by Cmdrd** [luadch/luadch#169]
When starting up v2.22, optional lib 'ssl' does not get loaded. Additionally the SSL portion of Luadch does not start, only the non-SSL portion. There is an errror in the error logs:

> [2022-03-19 | 10:36:43] scripts.lua: lua error in script 'etc_keyprint.lua': ././scripts/etc_keyprint.lua:20: loop or previous error loading module 'ssl' 
> [2022-03-19 | 10:36:43] server.lua: function 'addserver': luasec not found

I have tried to find a workaround but no luck so far.

**Comment by Cmdrd** [comment]
Here is the startup output:

> ./luadch
> init.lua: import libs
> init.lua: loaded 'adclib'
> init.lua: loaded 'unicode'
> init.lua: loaded 'socket'
> init.lua: import optional libs
> init.lua: loaded 'basexx'
> init.lua: import core
> init.lua: loaded 'const'
> init.lua: loaded 'mem'
> init.lua: loaded 'signal'
> init.lua: loaded 'doc'
> init.lua: loaded 'util'
> init.lua: loaded 'types'
> init.lua: loaded 'cfg'
> init.lua: loaded 'out'
> init.lua: loaded 'server'
> init.lua: loaded 'adc'
> init.lua: loaded 'scripts'
> init.lua: loaded 'hub'
> init.lua: init core modules
> init.lua: initialized 'util'
> init.lua: initialized 'cfg'
> init.lua: initialized 'hub'
> init.lua: initialized 'scripts'
> 
> Luadch v2.19 by blastbeat and pulsar (2007-2017)

**Comment by Cmdrd** [comment]
Resolved. I copied the directories incorrectly when updating, as seen in the last line of the startup output.

**Comment by Cmdrd** [comment]
Couple of years later and running into this issue again and unable to determine how it was resolved last time. The libraries and everything are where they are supposed to be but still getting the same issue.

**Comment by Cmdrd** [comment]
Having this issue even with just executing in the extracted downloaded file. All of the other libraries look like they're loading except for SSL/LUASEC @blasti

**Comment by Cmdrd** [comment]
Further debugging, getting the following:

`error loading module 'ssl.core' from file '././lib/luasec/ssl/ssl.so':
        libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by Cmdrd** [comment]
Alright, so this is everything I did to get this fixed is below for anyone else running into problems as I think debug logging should be more expansive to tracking down issues like this. As well this looks like a potential issue with Ubuntu 22.04, so anybody running into this problem, it is fixable, but the Ubuntu maintainers of the OpenSSL package look like they may have removed the libssl1.1/libcrypto1.1 shared libraries at some point. LuaDCH should also look to switching to linking to libssl3.so instead of libssl.so.1.1 but that's for another day I think.

In order to debug the issue, in core/init.lua in the following section:
```lua
    write "\ninit.lua: import optional libs"
    local succ
    for i, lib in ipairs( _optional ) do
        succ, ret = pcall( require, lib )
        _global[ lib ] = ( succ and ret ) or false
        _ = succ and write( "\ninit.lua: loaded '" .. lib .. "'" )
    end
```
I modified it to be the following to see what errors were occurring when loading the optional libraries (trying to see what happens when the SSL library is loaded:
```lua
    write "\ninit.lua: import optional libs"
    local succ
    for i, lib in ipairs( _optional ) do
        succ, ret = pcall( require, lib )
        write ( toString(succ) )
        _global[ lib ] = ( succ and ret ) or false
        _ = succ and write( "\ninit.lua: loaded '" .. lib .. "'" )
    end
```
Pretty crude but it did the trick, just outputting the success (or lack thereof) result importing the libraries. This then showed the following error during startup:

```
init.lua: import optional libs
ssl
false,error loading module 'ssl.core' from file '././lib/luasec/ssl/ssl.so':
	libssl.so.1.1: cannot open shared object file: No such file or directory
```
This means that the libssl.so.1.1 shared library isn't available, despite openssl being installed on this system. In order to resolve this issue, performing the following steps.

1. Find the locations of libssl.so.1.1 and libcrypto.so.1.1
```
locate libssl.so.1.1
locate libcrypto.so.1.1
```
2. Symlink one of the returned entries from each command output to a shared library location
```
sudo ln -s $libssl.so.1.1_location /usr/lib/x86_64-linux-gnu/libssl.so.1.1
sudo ln -s $libcrypto.so.1.1_location /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```
3. Reload the shared libraries 
```
sudo ldconfig
```

At this point, run luadch again and you should see that the SSL library has loaded successfully and your hub should be running successfully at this point, assuming no other issues. If you modified core/init.lua, you can revert the changes.

**Comment by blasti** [comment]
> Alright, so this is everything I did to get this fixed is below for anyone else running into problems as I think debug logging should be more expansive to tracking down issues like this. As well this looks like a potential issue with Ubuntu 22.04, so anybody running into this problem, it is fixable, but the Ubuntu maintainers of the OpenSSL package look like they may have removed the libssl1.1/libcrypto1.1 shared libraries at some point. LuaDCH should also look to switching to linking to libssl3.so instead of libssl.so.1.1 but that's for another day I think.
> 
> In order to debug the issue, in core/init.lua in the following section:
> 
> ```lua
>     write "\ninit.lua: import optional libs"
>     local succ
>     for i, lib in ipairs( _optional ) do
>         succ, ret = pcall( require, lib )
>         _global[ lib ] = ( succ and ret ) or false
>         _ = succ and write( "\ninit.lua: loaded '" .. lib .. "'" )
>     end
> ```
> 
> I modified it to be the following to see what errors were occurring when loading the optional libraries (trying to see what happens when the SSL library is loaded:
> 
> ```lua
>     write "\ninit.lua: import optional libs"
>     local succ
>     for i, lib in ipairs( _optional ) do
>         succ, ret = pcall( require, lib )
>         write ( toString(succ) )
>         _global[ lib ] = ( succ and ret ) or false
>         _ = succ and write( "\ninit.lua: loaded '" .. lib .. "'" )
>     end
> ```
> 
> Pretty crude but it did the trick, just outputting the success (or lack thereof) result importing the libraries. This then showed the following error during startup:
> 
> ```
> init.lua: import optional libs
> ssl
> false,error loading module 'ssl.core' from file '././lib/luasec/ssl/ssl.so':
> 	libssl.so.1.1: cannot open shared object file: No such file or directory
> ```
> 
> This means that the libssl.so.1.1 shared library isn't available, despite openssl being installed on this system. In order to resolve this issue, performing the following steps.
> 
>     1. Find the locations of libssl.so.1.1 and libcrypto.so.1.1
> 
> 
> ```
> locate libssl.so.1.1
> locate libcrypto.so.1.1
> ```
> 
>     2. Symlink one of the returned entries from each command output to a shared library location
> 
> 
> ```
> sudo ln -s $libssl.so.1.1_location /usr/lib/x86_64-linux-gnu/libssl.so.1.1
> sudo ln -s $libcrypto.so.1.1_location /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
> ```
> 
>     3. Reload the shared libraries
> 
> 
> ```
> sudo ldconfig
> ```
> 
> At this point, run luadch again and you should see that the SSL library has loaded successfully and your hub should be running successfully at this point, assuming no other issues. If you modified core/init.lua, you can revert the changes.

That's interesting, thanks for your effort! In case of SSL errors, first try to compile luadch from scratch on your Linux system. See here: https://github.com/luadch/luadch/issues/232#issuecomment-2385708150
