### ISSUE TITLE
Offline users don't get delregged

### ISSUE THREAD

**Issue by Ch0kehold** [luadch/luadch#17]
According to hubinfo, the hub has been online for at least a couple of days:
```
Uptime (complete):  12 days, 20 hours, 45 minutes, 50 seconds
Uptime (session):  9 days, 13 hours, 35 minutes, 4 seconds

```
However, since at least session started counting, a few users have been offline for more than the allowed time.
```
- [226]	[[1Mbit]KittensGotClaws]	[50]		[Outlaw]			[true]		[false]		[1 y, 0 m, 7 d, 15 h, 19 min]
- [227]	[[2Mbit]Nocken]	[20]		[USER]			[true]		[false]		[1 y, 0 m, 7 d, 12 h, 52 min]
- [228]	[[1Mbit]Thessan]	[20]		[USER]			[true]		[false]		[1 y, 0 m, 3 d, 18 h, 3 min]
- [229]	[[2.5Mbit]Bigsweed]	[20]		[USER]			[true]		[false]		[1 y, 0 m, 3 d, 9 h, 35 min]
```
This is in accordance with the 365 day limit on both level 20 and level 50 users.

I understand not running a scan and delreg at startup but it should at least delreg like it's supposed to while session is longer than time since violation occurred.
Or does session time have to be longer than 365 days for it to work?

**Comment by Sopor** [comment]
I have been trying to use the `Offline users` to clean out users but it won't work at all. It is very complex to explain every detail of the problem. I believe it is easier to test it and you will see it won't delete any users.

**Comment by Ninja-FSE** [comment]
i guess no one knows how to fix this?

**Comment by pulsar-de** [comment]
removed: "etc_offlineusers.lua"
added: "cmd_usercleaner.lua"
