### ISSUE TITLE
etc_trafficmanager.lua - Prevent BLOCKED users from receiving/replying searches

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#171]
When a user is `BLOCKED` they will still reply on searches and my client tries to download the file list, but because the user is blocked it can't download the file list. So, when `Automatically search for alternative bundle sources` is enabled it will match against blocked users too.

So, after a while i have several file lists in queue that never will be downloaded and i can also see them in the transfer view as `connection timed out`.

When a user is blocked they shouldn't receive any searches or they shouldn't send a reply (or both).

**Comment by pulsar-de** [comment]
> When a user is blocked they shouldn't receive any searches or they shouldn't send a reply (or both).

The second is not possible because the client sends the response "URES" via the UDP port, the hub doesn't notice anything. But the first is possible.
