### ISSUE TITLE
Ensure clients secure transfers availability

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#172]
I miss an option to prevent clients with no or disabled secure transfers from entering a hub.

Still investigating, but _maybe_ this can be done by checking ADCS in SU as https://adc.sourceforge.io/ADC-EXT.html#_adcs_symmetrical_encryption_in_adc says.

**Comment by blasti** [comment]
In theory, the hub cannot prevent unsecure transfers, as transfers are negotiated between clients.
In practice, you can enforce secure hub - client connections by open TCP TLS ports only. Most sane clients should then use secure client - client connections too.

**Comment by Tantrix** [comment]
> The hub cannot prevent unsecure transfers

Yes, I know.

But there is an option in ADCH++ to check if they are supported.

_suadcs - current value: 0 - disallow users that have disabled ADCS (TLS) support for file transfers_

> Most sane clients should then use secure client - client connections too.

Depends on client itself and its settings.

**Comment by blasti** [comment]
Ok, I will check this.

**Comment by Sopor** [comment]
```
	local adcs = string.find(su, 'ADC0') or string.find(su, 'ADCS')
	if li_settings.suadcs.value > 0 and li_settings.li_minlevel.value <= access.get_level(c) and not adcs then
		local stat = "Support ADCS forced"
		local str = "This hub requires the secure transfers option enabled in your client (its usually in Settings/Security Cerificates, enable 'Use TLS when remote client supports it' there) !"
		local type = "lim"
		local factor = 60
		local maxcount = 0
		maxrate = li_settings.suadcs_rate.value
		local minutes = li_settings.suadcs_exp.value
```

**Comment by blasti** [comment]
A strategy for such an option could be as follows:

- [ ] Only open TLS ports for hub
- [ ] Check for `ADC0` and `ADCS` in SU of INF, as well as in CTM and RTM
- [ ] Allow only clients which supply a keyprint (keyprint extension is needed to avoid man in the middle attacks)

**Comment by blasti** [comment]
As a tangential question, does anybody know how the current state of the [SUDP extension](https://adc.sourceforge.io/ADC-EXT.html#_sudp_encrypting_udp_traffic) is? (@maksis)

**Comment by Tantrix** [comment]
> Only open TLS ports for hub

Just FYI: secure transfers are in use regardless of adc:// or adcs:// address used. ApexDC++ is the only exception.

> Check for ADC0 and ADCS in SU

That was my initial doubt. 

Look, both clients have secure transfers enabled, but no ADCS SU shown: https://prnt.sc/zxRACbpSi7Xy

**Comment by Tantrix** [comment]
Aha, got it finally.

ADC0 SU goes away when TLS disabled.

And ADCS SU is announced just by ncdc yet.

> as well as in CTM and RTM

I think there is no need for that. It seems to be a resource-intensive operation by the way.

**Comment by pulsar-de** [comment]
I wrote a small script, maybe it helps you: [etc_client_su_check_v0.1 (english)](https://github.com/luadch/scripts/blob/master/zip/etc_client_su_check_v0.1%20(english).7z)

**Comment by Tantrix** [comment]
> I wrote a small script, maybe it helps you: [etc_client_su_check_v0.1 (english)](https://github.com/luadch/scripts/blob/master/zip/etc_client_su_check_v0.1%20(english).7z)

Thanks, will test it shortly.

**Comment by Tantrix** [comment]
Oops.

When

`[ "ADC0" ] = true,  -- If the client "Settings/Security/Use TLS" option is set, then the client sends this flag`

the script seems to be reacting exactly when this SU **is present**.

**Comment by pulsar-de** [comment]
Yes, thats true, sry...  :)

Try this one: [etc_client_su_check_v0.2 (english)](https://github.com/luadch/scripts/blob/master/zip/etc_client_su_check_v0.2%20(english).7z)

**Comment by Tantrix** [comment]
All good now.

Thanks.

**Comment by Tantrix** [comment]
Just came to mind.

1) Due to its nature, NATT SU should be checked for passive users only. Passive users are those whose **TCP4(6)** and **UDP4(6)** SU are missing.
2) Correct SU for NAT traversal feature is **NAT0**
