### ISSUE TITLE
New version 2.23 deployment - unregged users disconnect.

### ISSUE THREAD

**Issue by HadesDCH** [luadch/luadch#173]
Regs are ok but unreg users all get disconnect with error message     >>> no profile
Same with pinger  - soft does not parse client infos.

**Comment by pulsar-de** [comment]
fixed with: 09b4728a49263a4dc1d5cf40bbaa913bbbd705ec

for a quick an dirty fix you can do the following:

open `core/hub.lua` and search:
```lua
        else
            local bol, err = insertreguser( user, profile, cid, hash, nick )
            if not bol then
                user:kill( "ISTA 220 " .. escapeto(err) .. "\n", "TL-1" )
                return true
            end
        end
```
then replace with:
```lua
        elseif profile then
            local bol, err = insertreguser( user, profile, cid, hash, nick )
            if not bol then
                user:kill( "ISTA 220 " .. escapeto(err) .. "\n", "TL-1" )
                return true
            end
        end
```

**Comment by HadesDCH** [comment]
Using source from git. v 2.24 RC1 unregged users bug seems to be fixed however not the pinger:

[22:12] <[US]HubSecurity> [ FAILED AUTHENTICATION ]--> User:  Helsinki.v.11  |  IP:  <UNKNOWN>  |  CID:  TALLJIMTACE575FPNO7R32CLL54HO24LRDSMLDY  |  Reason:  No CID/PID/NICK/IP found in your INF.

Here is coded INF for ping that is being sent to hub:
 BINF 3MOP ID2T56TPEQU65NYFP5Z3ML2DH43XNNPHRU6PSPXKI PD5AC3A3B5T3NQEDCXESX7EVPAGFQ55ONBUQKS7IA NIFinland DEHelsinki SL3 SS8636211822332 SF100 HN1 HR0 HO0 VE++\s0.867 US5242 I40.0.0.0 SUADC0,TCP4,UDP4

**Comment by HadesDCH** [comment]
Is this because of Pinger nick change?

**Comment by Delitants** [comment]
> Using source from git. v 2.24 RC1 unregged users bug seems to be fixed however not the pinger:
> 
> [22:12] <[US]HubSecurity> [ FAILED AUTHENTICATION ]--> User: Helsinki.v.11 | IP: | CID: TALLJIMTACE575FPNO7R32CLL54HO24LRDSMLDY | Reason: No CID/PID/NICK/IP found in your INF.
> 
> Here is coded INF for ping that is being sent to hub: BINF 3MOP ID2T56TPEQU65NYFP5Z3ML2DH43XNNPHRU6PSPXKI PD5AC3A3B5T3NQEDCXESX7EVPAGFQ55ONBUQKS7IA NIFinland DEHelsinki SL3 SS8636211822332 SF100 HN1 HR0 HO0 VE++\s0.867 US5242 I40.0.0.0 SUADC0,TCP4,UDP4

Same problem, and not just with pinger, but users too. 2.24 is terrible.
