### ISSUE TITLE
cmd_nickchange.lua - TL-1

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#182]
When you change the nick of a user there is no reason to send TL300 to the user because the user must manually change the nick before he can login again. It will only be a bunch of annoying messages in the OpChat.

Please change it to TL-1.

**Comment by pulsar-de** [comment]
True, thanks m8.

**Comment by pulsar-de** [comment]
fixed with: f06dc2bc46f8018a1cb957b258c1d49e462dfa0c
