### ISSUE TITLE
Include email address in ACCOUNT when register a new user

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#185]
When register a user it will show show the account info that i can send to the user:
```
=== ACCOUNT ============================================================================

    Nickname: MyOwnNick
    Password: h963gd795Rxp8ex61Kwo

    Level: 20  [ REG ]

    Hubname: Luadch Hub
    Hubaddress: 

	- TCP IPv4:

	adc://your.host.addy.org:5000

	- SSL IPv4:

	adcs://your.host.addy.org:5001

	- optional Keyprint available:

	/?kp=SHA256/FXQ6JVZYKCFZXU3HGHRIXRVVF76GA6QRVFCZ6PHHPLRCJF5YHDXQ


============================================================================ ACCOUNT ===
```

In cfg.tbl i can add an email address `hub_email = "hub@mail.com"` and that is nice, but it would be even nicer if there was an option to include it in the account info i send to a user.

Maybe add the `Hub email: hub@mail.com` below the keyprint...

**Comment by Kungen123** [comment]
yes i think that be nice

**Comment by pulsar-de** [comment]
added with: 66d90cc953499a2a0797017ddef17fc70baa2202
