### ISSUE TITLE
cmd_usercleaner.lua - Remove blocked users from etc_trafficmanager.tbl

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#188]
When deleting a user that exists in the traffic manager the user will also be removed from the block list (#95).

If i instead use `cmd_usercleaner.lua` the user will not be removed from the `etc_trafficmanager.tbl`

**Comment by pulsar-de** [comment]
You're absolutely right, that should of course be part of it.

```
- changed: "scripts/cmd_usercleaner.lua"
    - remove reg description if it exists (cmd_reg_descriptions.tbl)
    - remove ban if it exists (cmd_ban_bans.tbl)
    - remove block if it exists (etc_trafficmanager.tbl)
       - fix #188 / thx Sopor

```
Fixed: f87c86163d58b0e871b4ab5f9dfcb0a12acf2d09
