### ISSUE TITLE
Valid UTF-8 messages are ignored

### ISSUE THREAD

**Issue by maksis** [luadch/luadch#19]
Try to send a chat message containing a UTF-8 emoji, such as 🌍, and it will never be displayed. No error messages. The latest versions of ADCH++ and uhub (git) are working fine.

If you use AirDC++, you must have the latest dev build (or use the Web UI).

**Comment by blasti** [comment]
cannot confirm using airdc 3.31. did not test the airdc dev build though. is it available somewhere?

**Comment by maksis** [comment]
http://builds.airdcpp.net/updater/updater_x64_3.40a-96-g784ad.zip

**Comment by blasti** [comment]
ok i tried airdc 3.40a-96.

i copied a utf8 emoji from the internet into mainchat. symbol is not shown in mainchat text line (only some placeholder rectangle). after sending it, luadch reports invalid utf8 string and discards the message.

if i do the same with airdc 3.31, the symbol is not shown in the mainchat text line too, but an "empty" message will be broadcasted by luadch. luadch reports valid string and broadcasts it.

i tried also some utf8 chars from windows charmap. some are not shown in both airdc 3.31 / 3.40 at all, even no placeholders. some are shown wrong. some right. but all can be broadcasted, no invalid utf8 message from luadch.

by the way, luadch uses the same code as uhub to check for valid utf8, see [https://github.com/luadch/luadch/blob/master/adclib/adclib.cpp#L49](https://github.com/luadch/luadch/blob/master/adclib/adclib.cpp#L49)

**Comment by maksis** [comment]
When comparing the validation code, the logic looks somewhat different to me (especially after the commit "Add support for 4 byte UTF-8 characters and stricter character checking"): https://github.com/janvidar/uhub/blob/master/src/util/misc.c#L66

AirDC++ 3.31 is known not work correctly, which is why I mentioned it in the report.

I'm able to paste the emoji without seeing any placeholder rectangles:

![image](https://cloud.githubusercontent.com/assets/5640804/23276070/91be2618-fa11-11e6-9622-de59edb94ecb.png)

**Comment by maksis** [comment]
Is this issue supposed to be closed?

**Comment by blasti** [comment]
as i dont see how to reproduce the problem, i dont see how to fix it. once could use the latest uhub utf8 validation code tough.

**Comment by maksis** [comment]
So the issue is that you can't copy-paste the symbol as it is? Did you try the Web UI, as I also suggested? If you can't copy-paste the symbol even in the browser, then it won't obviously help. Do you have an exotic system setup or old Windows version? [Character information](http://www.charbase.com/1f30d-unicode-earth-globe-europe-africa) for a possible validation function test.

**Comment by blasti** [comment]
correct, i cannot copy paste this symbol as it is. i tried different browsers, on windows 7 and linux.
looks always like this rectangle: [http://imgur.com/a/rxDzA](http://imgur.com/a/rxDzA)
similar rectangle appears in airdc 3.31/3.4.

**Comment by maksis** [comment]
Ah. But yes, I believe that updating the validation code will fix the issue.

**Comment by blasti** [comment]
ok, i need to look into this

**Comment by blasti** [comment]
updated validation code in [https://github.com/luadch/luadch/commit/52aabc3a21d3e601ed4b30fafa13860920baec1e](https://github.com/luadch/luadch/commit/52aabc3a21d3e601ed4b30fafa13860920baec1e)

**Comment by blasti** [comment]
ok the new validation code of uhub  does not work properly.  many scripts are now reported to be non utf8, despite the fact that they are. either the original code is buggy, or I did a bad copy paste job.

**Comment by maksis** [comment]
Validation done by clients based on DC++ is rather simple: https://sourceforge.net/p/dcplusplus/code/ci/default/tree/dcpp/Text.cpp#l260

**Comment by blasti** [comment]
See also #158 and https://github.com/luadch/luadch/commit/8aad5d34b967765d5b4860f3668b983eca1b5535
