### ISSUE TITLE
Hub update need to count complete/session simultaneous

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#190]
The hub uptime complete is not counting hours until you shutdown/restart the hub (i assume it takes the session time and add to the complete time, correct?)
        Uptime (complete):  	0 years, 0 days, 0 hours, 0 minutes, 0 seconds
        Uptime (session):  	0 years, 5 days, 10 hours, 39 minutes, 29 seconds

If for some reason Luadch crash or i get a power failure the time will get lost and if i want to see the complete uptime i'm forced to take the complete time and add the session time manually.

An uptime counter should have one complete and one session and both should count up simultaneous, but the difference is that the session will start from 0 at shutdown/restart.

**Comment by pulsar-de** [comment]
Fixed with: f5317c057b7b7b8421cbf815a93d6e6f1273db65
and: 169250ab70702957092ad02a4cb38a9745e11736
