### ISSUE TITLE
`user.tbl.bak` not working

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#191]
The `user.tbl.bak` never gets updated (verified on four different hubs).

I have `user.tbl.bak` files that are several month old.

**Comment by maldond** [comment]
Same here on v2.24 RC3 (windows 10)

**Comment by Sopor** [comment]
It seems to work on `Luadch v2.23 [RC9]`

**Comment by pulsar-de** [comment]
The backup of the `user.tbl` is always updated when the hub is started (even with a restart). This works as it should (testet with 2.24 [RC3] under Windows 10 and Linux). Please test that. If that doesn't work, it may be due to missing write permissions (especially under linux).

An additional update would be conceivable whenever a new user is registered. I think that would be a useful addition

**Comment by pulsar-de** [comment]
The `user.tbl.bak` is now updated when a user is registered or deleted.

**Comment by Sopor** [comment]
It is not working as it should. I even wrote it is working on older version, but not on 2.24.

Do you really think we would report it if it was working?

**Comment by pulsar-de** [comment]
Have u tried the new one? Use a clean and fresh 2.24 RC4 then try:

- register some users
- delreg one of them
- make a restart / shutdown

Check the user.tbl / user.tbl.bak after each step...

Works fine here on Windows and Linux.

**Comment by Sopor** [comment]
So, you mean it won't update when you register or delete a user? Yes, now it do it, but before that?

**Comment by pulsar-de** [comment]
I updated my online Hub and use a local testhub (clean). On both it works fine...

That's why I assumed you should test it with a clean version to see if it works for you. If it works, then it proves that you missed something when "updating" your existing version.

**Comment by Sopor** [comment]
I assumed it did it on every changes you made to the `user.tbl` and not only when you restart/shutdown the hub.

That explains why it didn't worked. I will try the new version.

**Comment by sebm123** [comment]
> The `user.tbl.bak` never gets updated (verified on four different hubs).
> 
> I have `user.tbl.bak` files that are several month old.
RUN.EXE
