### ISSUE TITLE
New LUADCH v2.17 [2016-01-21] 

### ISSUE THREAD

**Issue by dchublistdotorg** [luadch/luadch#2]
I downloaded it - edited config changed port and hub starts fine however cant connect to it using dc/++ stated connection timed out. What am i doing wrong?

**Comment by Sopor** [comment]
Luadch use TLS v1.2 as default and latest DC++ have no support for TLS v1.2. Either change to TLS v1.0 or use another DC client. [AirDC++](https://github.com/airdcpp/airgit/releases) will work with TLS v1.2.

**Comment by pulsar-de** [comment]
For more informations read this fixed DC++ issue:
[https://sourceforge.net/p/dcplusplus/code/ci/285f7c38fc3fff087d772a1d4c76ee5761494fea/](url)
And here is the Launchpad conversation about it:
[https://bugs.launchpad.net/dcplusplus/+bug/1484807](url)
