### ISSUE TITLE
Forward commands correctly based on their type

### ISSUE THREAD

**Issue by maksis** [luadch/luadch#21]
The current forwarding logic with full hardcoded FOURCC codes feels really NMDCish and violates the protocol specifications. The user won't even be notified if the message wasn't forwarded so it's hard for him to recognize that the problem lies in the hubsoft.

**Comment by blasti** [comment]
can you give an illustration of what you mean?

**Comment by maksis** [comment]
> Clients must ignore unknown/badly formatted messages. Hubs must ignore invalid messages and should dispatch unknown messages according to their type.

http://adc.sourceforge.net/ADC.html#_general

**Comment by blasti** [comment]
luadch should dispatch unkown parameters since [https://github.com/luadch/luadch/commit/c0dbf3b1545c410214ebcf45c74a26ce2f3b786b](https://github.com/luadch/luadch/commit/c0dbf3b1545c410214ebcf45c74a26ce2f3b786b)

**Comment by maksis** [comment]
But not unknown FOURCC codes, right? https://github.com/luadch/luadch/blob/master/core/hub.lua#L1736

**Comment by blasti** [comment]
if you mean by FOURCC something like "BMSG", then you can find [here](https://github.com/luadch/luadch/blob/master/core/hub.lua#L1736), which are dispatched.

it is up to the hub to decide, whether it dispatches unkown stuff or not.

>  Hubs ... should dispatch unknown messages according to their type.

as far as i read this, there is no violation to not dispatch unknown stuff

**Comment by blasti** [comment]
do you have a useful example of a FOURCC, which you would like to see dispatched by luadch?

**Comment by night-z** [comment]
It breaks the extendability of ADC protocol without the hubsoft constantly updating if it doesnt forward those commands. Who can say you will be there to add every new command there will be?

**Comment by maksis** [comment]
```
    DSCH = function( user, adccmd, targetuser )
        if not scripts_firelistener( "onSearch", user, adccmd ) then
            targetuser.write( adccmd:adcstring( ) )
        end
        return true
    end,
    DRES = function( user, adccmd, targetuser )
        if not scripts_firelistener( "onSearchResult", user, targetuser, adccmd ) then
            targetuser.write( adccmd:adcstring( ) )
        end
        return true
    end,
```

As a script writer, I would expect the `targetuser` parameter to be available for both of those D-type messages. `DINF` is another perfectly valid code that is not handled at the moment and would cause the same inconsistency for the scripts.

Assume the following generic code, that would be executed for all handled messages:

```
if not scripts_firelistener( cmd, sender, targetuser, adccmd ) then
```

... where `cmd` would be the three letter command (such as SCH) and `targetuser` would be null for messages that are targeted for all users. It should provide better consistency and you could then forward the message only based on the type.

I'm having trouble seeing the benefits of your current approach. It seems to make your code more complicated, scripting API inconsistent and breaks client features. Can you name the actual *benefits* that you are getting from it?

**Comment by blasti** [comment]
@night-z  in the worst case one can simply fork luadch? we are talking about free software here.

at the moment i dont see the benefit to simply forward every message without checking or progressing it. 

the current approach in the `hub.lua`  and `adc.lua` works like a whitelist, and i am happy with that.

if you name me concrete examples you want to have forwarded i will look at it and add it.

what might be an improvement is to notify the client about blocked messages. i understand this.

@maksis  you are talking about design decisions made 10 years ago, and one could argue forever, what would be the best.

your approach is generic and i understand it, and i also had that idea in the beginning (and i tried it if i recall correctly). but i decided against it. the idea of the current approach is it, to make the life of scripter easier by additional abstraction (it made **my life** easier at that time). every scripter knows from good old ptokax times, what an "onSearch" event might be. no scripter will know what a "BSCH" event is, not 10 years ago, and even not today.
also, i dont expect a scripter to know, that he has to take care about "FMSG" and "BMSG" separately,
if he simply wants to scan the actual message for bad words or whatever.

so the benefit was (and is), that you dont need to remember obscure FOURCCs and other quirks and glitches of the ADC portocol. if one wants to write scripts in your generic way, one would have to. and i certainly dont want to.

anyway, i dont see a problem in adding your idea at top of the currect approach, like this:

```
DRES = function( user, adccmd, targetuser )
        if not scripts_firelistener( cmd, adccmd, user, targetuser ) then
        ...
        end
        if not scripts_firelistener( "onSearchResult", user, targetuser, adccmd ) then
            targetuser.write( adccmd:adcstring( ) )
        end
        return true
    end,
```

then you can easily write your scripts in your way.

**Comment by maksis** [comment]
> also, i dont expect a scripter to know, that he has to take care about "FMSG" and "BMSG" separately

That's exactly not what they should be doing. The type just tells the hubsoft how to forward the command (and is not part of the actual command), which is why I wrote

> ... where `cmd` would be the three letter command (such as SCH)

Naturally the type can be provided separately, if needed. The actual commands (SCH, MSG, CTM...) should be easy to understand.

Forwarding commands based on the type in ADCH++: https://sourceforge.net/p/adchpp/code/ci/default/tree/adchpp/ClientManager.cpp#l64
Handling of commands (only the three letter command is used): https://sourceforge.net/p/adchpp/code/ci/default/tree/adchpp/ClientManager.cpp#l217

Forwarding commands based on the type in uhub: 
https://github.com/janvidar/uhub/blob/master/src/core/route.c#L22
Handling of commands (note that the "default" case will still take care of routing all unknown commands):
https://github.com/janvidar/uhub/blob/90d05c9a19d3f72e3bdc89e4906c9e254e6a7f10/src/core/hub.c#L59-L143

**Comment by blasti** [comment]
ok, if one does not listen for the actual FOURCC event, but only for command event, scripting gets even _more_ ugly.

in current approach, if i listen for mainchat messages in a script, for instance because i want to deflood the mainchat, i simply listen for "onBroadcast". 

if i would listen for FOURCC events, i would need to listen for "FMSG" and "BMSG".

using your suggestion, i would listen to "MSG", then look for the type, and discard "E" and "D" and progress "F" and "B". 

there might be situations, where your generic approach makes sense. but in most cases i wouldnt do this.
its simply not readable, let alone fun.

**Comment by maksis** [comment]
That's still a bit different than my original (quick) proposal.

```
onMessage( "MSG", sender, targetuser, adccmd ) {
  if (targetUser) {
    //PM
    return;
  }

  // Public message
}
```

(I'm not familiar with LUA)

I would avoid using the message types as much as possible. I'm sure that are also ways to make the idea better. The main point was that such listener could also be used to allow scripts to handle "unknown" messages as well. 

Possibly there could be a script that lists "known" command names and reports "unknown" ones in the feed. If the hub owner sees an unknown command that he doesn't like, he could use the script to block forwarding of such messages. That would allow much greater extensibility.

**Comment by maksis** [comment]
I've been initially considering to extend the [AirDC++ API](http://docs.airdcpp.apiary.io/#) to handle raw ADC commands, that could be used to exchange custom data with the hub or with other users. That would allow scripts writers to even develop their own ADC extensions.

Enabling such API functionality in hubs using a hubsoft that is not built to be extensible would make no sense though. It certainly makes sense that the hub owner may not want to have every possible custom extension to be used in the hub, but I think that there are ways to handle that properly in the hubsoft (such as the idea I mentioned in the previous post).

**Comment by blasti** [comment]
i always thought that if one wants to extend ADC, one hands in a proposal at dcbase or elsewhere, then implementing it using something like HSUP ADBASE...  etc pp. what you talking about sounds like complete freedom to do whatever is possible.

**Comment by night-z** [comment]
Its pretty much impossible to develop and test new extensions if it needs hub side changes first. It also takes the interest from developing such things when you have to wait until hubsoft forwards it, then you have to wait until hubowners upgrade their hubsoft, that can take even a year or more.

Handling unknown FourCC by sending it to scripts listener sounds like a reasonable solution for me, its then easy for the scripters to handle the commands if necessarry.

**Comment by maksis** [comment]
> i always thought that if one wants to extend ADC, one hands in a proposal at dcbase or elsewhere, then implementing it using something like HSUP ADBASE... etc pp. what you talking about sounds like complete freedom to do whatever is possible.

Hmm... are you talking about the scripting API? DC++ has had a plugin API for years and ADC extensions have been implemented on top of it (it's probably safe to assume that Luadch ignores those extensions without even checking the code). I'm not sure that how any of this affects the process of creating ADC extensions.

I also wrote

> It certainly makes sense that the hub owner may not want to have every possible custom extension to be used in the hub, but I think that there are ways to handle that properly in the hubsoft (such as the idea I mentioned in the previous post).

> Possibly there could be a script that lists "known" command names and reports "unknown" ones in the feed. If the hub owner sees an unknown command that he doesn't like, he could use the script to block forwarding of such messages. That would allow much greater extensibility.

A concrete (verbose) example:

```An unlisted protocol command OIR was received from the user XX: "DOIR CCCC BBBB mslive EMexample@live.com". Unlisted commands are not rejected. To skip logging commands of this type, save the command by typing "+allowcmd OIR" or "+blockcmd OIR".```

```An unlisted support ONID was received from the user XX. Unlisted extensions are not rejected. To skip logging supports of this type, save the support by typing "+allowsup ONID" or "+blocksup ONID".```

An option to block unknown commands by default would probably make sense only for users who are running (mostly) unmonitored public hubs.

**Comment by blasti** [comment]
ok i changed the forward logic

added a generic script listener ("onIncoming")

added blacklist to hub_cmd_manager, blocks same adc commands as uhub

see [https://github.com/luadch/luadch/commit/0b7cf2206404f073eebbbe633c90447b76a99b4a](https://github.com/luadch/luadch/commit/0b7cf2206404f073eebbbe633c90447b76a99b4a)

**Comment by maksis** [comment]
👍

**Comment by maksis** [comment]
What kind of plans do you have in regards of getting this change released? I'd like to start recommending Luadch, but it's somewhat awkward given that certain client features are blocked with the current release version.

**Comment by blasti** [comment]
the next release of the latest git version is scheduled for this week.
