### ISSUE TITLE
Blank/empty messages trigger "bad argument #1" error

### ISSUE THREAD

**Issue by ryehamstrawberry** [luadch/luadch#211]
I noticed when sending a blank message (e.g. consisting of a space or carriage return) that the following error is returned via SecurityBot:
` ././scripts/etc_chatlog.lua:299: bad argument #1 to 'byte' (string expected, got nil) (listener: onBroadcast; script: 'etc_chatlog.lua')`

It would be useful if this error was addressed, as there are numerous situations where sending an empty message is useful (breaking up long messages, etc.).

---
Version: Luadch v2.24 [RC4]

**Comment by ryehamstrawberry** [comment]
After further testing, the issue seems to appear only for hubowners on Luadch v2.24 [RC4] (possibly other beta versions too).

I cannot reproduce the error as an OP or REG user on Luadch v2.21 stable or as a REG, OP, or ADMIN user on Luadch v2.24 [RC4].

**Comment by Sopor** [comment]
You can find a temporary fix on my [Github page](https://github.com/Sopor/luadch-scripts)
