### ISSUE TITLE
I want to implement ChatBot-GPT-4.0 to Luadch

### ISSUE THREAD

**Issue by Boca-NeedM** [luadch/luadch#219]
I want to implement ChatBot-GPT-4.0 to Luadch..
So i let him write a script (i'm no programmer)
Here is the script ChatGPT wrote:

------------------------------------------------------------------------------------------------
local http = require("socket.http")
local ltn12 = require("ltn12")
local json = require("json")

local api_key = "Secret-key"
local model = "text-davinci-003"
local prompt = "The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.\n\nHuman: Hello, who are you?\nAI: I am an AI created by OpenAI. How can I help you today?\nHuman: I'd like to cancel my subscription.\nAI:"
local temperature = 0.9
local max_tokens = 150
local top_p = 1
local frequency_penalty = 0.0
local presence_penalty = 0.6
local stop = {" Human:", " AI:"}

-- Create the request body as a Lua table
local request_body = {
  prompt = prompt,
  temperature = temperature,
  max_tokens = max_tokens,
  top_p = top_p,
  frequency_penalty = frequency_penalty,
  presence_penalty = presence_penalty,
  stop = stop,
  model = model
}

-- Encode the request body as JSON
local request_body_json = json.encode(request_body)

-- Set up the HTTP request headers
local headers = {
  ["Content-Type"] = "application/json",
  ["Authorization"] = "Bearer " .. api_key
}

-- Make the HTTP request to the OpenAI API
local response_body = {}
local success, status_code, response_headers, status_text = http.request {
  url = "https://api.openai.com/v1/engines/" .. model .. "/completions",
  method = "POST",
  headers = headers,
  source = ltn12.source.string(request_body_json),
  sink = ltn12.sink.table(response_body)
}

-- Check for errors and parse the response
if success and status_code == 200 then
  local response_json = table.concat(response_body)
  local response = json.decode(response_json)
  local generated_text = response.choices[1].text
  print(generated_text)
else
  print("Error: " .. status_text)
end
------------------------------------------------------------------------------
I named the script cmd_chat.lua and put it in the script dir.
But now i'm stuck, i don't know how to proceed..
Who can help me..?

Kind regards,
Boca from NeedM hub.
adcs://86.107.187.54:5001

**Comment by blasti** [comment]
I won't fix ChatGPT nonsense. If you want to write a script for luadch, study a small script in the `scripts` folder. Create a new and modified one, add it to your `cfg.tbl`, reload your hubs settings (or restart the hub)  and find out what happens.
