### ISSUE TITLE
ungag won't work if the user is offline

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#22]
If i gag a user and the user goes offline i can't ungag until the user is online again. Quite annoying if i have to sit and wait for the user to come online again to ungag the user.

**Comment by blasti** [comment]
This script itself is annoying and needs to be kicked out of the core distribution of luadch. I will not touch this.

**Comment by Sopor** [comment]
I don't see this script as an annoying script. It is very useful when you want to mute a user. So please don't remove it...

**Comment by blasti** [comment]
ok. why not just temp ban the offending user?

**Comment by Sopor** [comment]
Then you can say the same thing on every commands, why not do this, or this, or this instead? A software must have different options because we all do different things.
