### ISSUE TITLE
Zero2W

### ISSUE THREAD

**Issue by Boca-NeedM** [luadch/luadch#225]
Does someone has a working Luadch on a RaspberryPi Zero2W ?
I got:

@Zero2W ~] > cd /luadch
@Zero2W luadch] > ./luadch
-bash: ./luadch: No such file or directory

( http://86.107.187.54:8890 )

- On my RaspberryPi3 Luadch works fine.

**Comment by Sopor** [comment]
You can try this one! 
[Luadch-2.24-RC4-20230130-ARM.tar.gz](https://github.com/luadch/luadch/files/12552494/Luadch-2.24-RC4-20230130-ARM.tar.gz)

I assume you have made luadch executable `chmod +x <file_name>`?

**Comment by Boca-NeedM** [comment]
(executable, yes)

I can always try 2.24
Thanks!

**Comment by Sopor** [comment]
If you get it to work don't forget to replace `etc_trafficmanager.lua` with this [one](https://github.com/luadch/luadch/issues/197#issuecomment-1280029485)
to avoid `File not available` and `SECURITY WARNING`

**Comment by Boca-NeedM** [comment]
Thanks!


7 sep 2023 21:33 van ***@***.***:

**Comment by Boca-NeedM** [comment]
Nop, i think i have to compile it somehow.
I don't know much about compling.
I'm in the dark right now. ;)

**Comment by Boca-NeedM** [comment]
Is Luadch 32bits or 64bits software?
I have now 64bits on my Zero 2W, maybe that's the problem.
I can try compling but i don't know how to do this.


7 sep 2023 21:33 van ***@***.***:

**Comment by Sopor** [comment]
The one i sent you was 32-bit ARM, but i have another for 64-bit.

Maybe you need to compile your own?

**Comment by Boca-NeedM** [comment]
Yes, i think i got it now..
It need some fine tuning but first result look good.
Thanks!


8 sep 2023 21:11 van ***@***.***:

**Comment by blasti** [comment]
Best is to compile luadch from scratch on your Linux machine. Here is an explanation how to do it on Debian based systems:

https://github.com/luadch/luadch/issues/232#issuecomment-2385708150
