### ISSUE TITLE
NeedM Hub

### ISSUE THREAD

**Issue by Boca-NeedM** [luadch/luadch#229]
Tip: v2.24 work fine on a 64bit Raspberry Pi Zero2W
NeedM-Private is running Luadch v2.24 [TLS: v1.3] on a 64bit Raspberry Pi Zero2W - Powerconsumption 0,5 watt per hour -

You can connect via IPv4 using adc://86.107.187.54:5000 
or encrypted via adcs://86.107.187.54:5001
and via IPv6 using adc://[2a00:bba0:1204:3700:df76:a9ed:b06c:c157]:5002 
or encrypted via adcs://[2a00:bba0:1204:3700:df76:a9ed:b06c:c157]:5003

Just saying.. good job done..

**Comment by blasti** [comment]
Great!
