### ISSUE TITLE
TRAFFIC MANAGER - can't block/unblock users that are offline

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#23]
TRAFFIC MANAGER can't block users that are offline. Sometimes you need to do that but as it is now this is not possible. I believe it is the same when i unblock.

**Comment by Sopor** [comment]
If a user is blocked and this user later will be delregged i can't remove this user from the traffic manager. So this user will continue to show up as a blocked user even if it not exists anymore.

**Comment by blasti** [comment]
Ok. Probably the best would be to add  an "onDelreg" event, so handle such issues.

**Comment by pulsar-de** [comment]
added new listener "onReg" + "onDelreg"
