### ISSUE TITLE
MSG viewable in Chatlog after setting msgmanager_permission_main=false

### ISSUE THREAD

**Issue by technicianGF** [luadch/luadch#27]
Hi, after setting msgmanager_permission_main=false, the users can't write main chat MSG, OK, but I still can see their blocked MSG in chatlog on login right after motd.

**Comment by blasti** [comment]
fixed in 1df22e40bfa838c7fa6f828f91fc17b04392e0fd

just place in cfg.tbl the entry `etc_msgmanager.lua` before `etc_chatlog.lua`
