### ISSUE TITLE
USER LOGIN INFO - Client CCPM:

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#28]
Luadch 2.19 will not show the CCPM in the `USER LOGIN INFO` if it is Yes or No.

So you need to remove `Client CCPM:   %s` or add some new code into the `etc_userlogininfo.lua` to re-enable `Client CCPM` at login.

**Comment by Tadies** [comment]
Thank You Sopor for this post.....

**Comment by blasti** [comment]
checkout 146e687bad8d6013ee7178b0fc8c5228192400f1
