### ISSUE TITLE
disable one or two command prefix [+!#]

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#33]
It should be possible to disable [+!#] if i want to use it with another bot. As it is now all three chars work but it should be possible to turn of one or two command prefix.
Maybe it is even better if Luadch ignored command it won't recognize?

**Comment by blasti** [comment]
If you want luadch to ignore unknown commands, just dont use the script

`etc_unkown_command.lua`

You can comment it out in the `cfg.lua`. The downside in deactivating this script is, that if somebody mistypes a command in the mainchat, it might be visible to all.
