### ISSUE TITLE
Sender: cmd_pm2offliners

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#34]
When doing a `PM to offliner` it will show this message in the Hubbot window
`Offline PM No. 1  |  Sender: cmd_pm2offliners  |  Date: 2017-06-17 / 14:59:33`
and i don't think it should show `cmd_pm2offliners` as the sender, it should show the user that have sent the PM, right?

I could also read in the main window from the Hubbot:
`You have [1] new offline message(s) waiting for you.`
Why do it show this to me? I was the sender, not the receiver.

I'm running Luadch 2.19

**Comment by blasti** [comment]
Not a bug. The sender will get informed by "cmd_pm2offliners" about the delivery.
And "You have [1] new offline message(s) waiting for you." means, that the script has a message for you.
Either you get informed about a successful delivery, or you receive an offline message.
