### ISSUE TITLE
TRAFFIC MANAGER - wrong message when blocking a user that is already blocked

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#37]
If i try to block a user that is already blocked i will get this message
`Traffic Manager: The level of this user is already auto-blocked.`.
This message is completely wrong to show here. A new message should be added with a proper message:
`User %s is already blocked by %s` = `User Arnold is already blocked by [OP]Oden`.

**Comment by pulsar-de** [comment]
Should be fixed now.

Greets
