### ISSUE TITLE
Request : FreeBSD binary

### ISSUE THREAD

**Issue by ghost** [luadch/luadch#4]
Hi,

Is there any chance we could get a FreeBSD binary along with the ones that are already provided such as Debian and RaspberryPi etc..

I love luadch but I am having a very hard time compiling it from source on FreeBSD.

Thanks.

**Comment by blasti** [comment]
ok, i did some tests on an fresh default install of freebsd 10.3 64bit.
added a new shell script called

build_with_freebsd.sh

to the root directory of the luadch source (its basically the same as the gcc build script).
to compile luadch on freebsd, do the following:

`# pkg install git rsync`
`$ git clone https://github.com/luadch/luadch.git`
`$ cd luadch`
`$ chmod u+x compile_with_freebsd.sh`
`$ sh compile_with_freebsd.sh` 

you can then find the hub in the build_gcc folder. to avoid strange messages during startup of the hub,
goto cfg.tbl and disable the cmd_hubinfo script. it seems not to work with freebsd, need some fix.
