### ISSUE TITLE
usersearch - will reveal password for other users with the same level

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#40]
If i try to get the account info from the user list `+accinfo sid NHSR` with the same level as myself (60) or higher i get this: `You are not allowed to use this command or the target user has a higher level than you.`
This will make sense but if i instead use `+usersearch` it will even show the password on the same level as myself:
```
	Nick: [OP]Jesus
	Level: 60
	Password: Noh83wfx2jS49pO5A857
	Regged by: [Owner]God
	Regged since: 2017-08-17 / 12:31:07
	Last seen: user is online
```
It seems to not reveal the password if the user have a higher level than myself or at least it won't show the level 100 password:
```
Level: 100
Password: Not allowed to view
```
If `cmd_accinfo_permission` is set to 50 for level 60 users (this is the default value) it shouldn't be possible to see the password from users with higher level when i run `+usersearch`.
The only access info that is important to hide from other users with the same level is the password and by using `+usersearch` you can easily reveal it.

**Comment by precla** [comment]
Will this do the trick?
Instead of:
`( user_level >= u.level ) and ( u.password or msg_unknown ) or msg_no_allowed,`
do:
`( user_level > u.level ) and ( u.password or msg_unknown ) or msg_no_allowed,`

https://github.com/luadch/luadch/blob/master/scripts/cmd_usersearch.lua#L178
