### ISSUE TITLE
cmd_reg.lua - OP's can add/change/remove comments on higher level than himself

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#42]
I have level 60 and i can run `+reg desc <username> <comment>` to change comment on a level 100 users. If i try to view the comment i get this message `You are not allowed to use this command or the target user has a higher level than you`.
A level 60 user can't create a level 100 account so it should not be able to add, create or remove any comments either.

**Comment by Kungen123** [comment]
Yes i think thats wrong so that need too be fixed
