### ISSUE TITLE
cmd_usersearch.lua

### ISSUE THREAD

**Issue by Kungen123** [luadch/luadch#43]
if i have level 60 as Op and looking for a user and it turns out he has a higher level than me for ex level 80 . this should not be shown too mee at level 60.

**Comment by Sopor** [comment]
I would suggest that not showing any info about the same or higher level. Same way the `Show Accinfo` doesn't show anything. It should only show the nick.

**Comment by blasti** [comment]
Ok I checked this. Informations from higher level users are shown in usersearch, except the password. Whats the problem with that solution? Why show nothing/show only the nick?

**Comment by Sopor** [comment]
Info that is not available with `+accinfo nick` should not be available through another command like +usersearch. So i don't understand why this should have an option https://github.com/luadch/luadch/pull/52 ?

**Comment by blasti** [comment]
Its a matter of taste. With an option, you can choose.

**Comment by Sopor** [comment]
In that case the +accinfo should also have an option... A user with higher level should not be able to get info on the same level or higher. All other commands works like this so why not +usersearch ?

**Comment by blasti** [comment]
Ok sounds reasonable, you should open another issue for it.
