### ISSUE TITLE
Add port number that is hidden for the users

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#44]
No DC client will allow you to add the same address twice in the favorite hubs. If you are an Owner of a hub you always test functions to see if they works or how they works and i use another port number when i do that. If i add another port number this will also be visible to other users when they run `+hubinfo` and when they get a new account registered. So it would be perfect if it was possible to add ports that was hidden for all users.

**Comment by blasti** [comment]
Why do you use/need another port to test stuff?
You are aware, that users can perform port scans, and find you "hidden" port if it is open?
Right now I see no good reason to add this feature.

**Comment by Sopor** [comment]
Yes, they can port scan but they will not get any answers. All ports (except the original hub port) are blocked except for those that have access to the hub server (ConfigServer Security & Firewall make this possible). That is why i don't want to show this port to the users so they think it is open for them to use and when they can't connect they think something is wrong.

**Comment by blasti** [comment]
Ok, but what is the point in using another port?

**Comment by Sopor** [comment]
I can create two favorite hub entries that make me login into the same hub but with different names (of course not at the same time). DC clients won't allow you to create two favorites with the same address. I can of course run one more DC client and hash a new share but it is much easier if i could logout and login with a different name in the hub. Then you suggest: "use the Quick connect". It is not possible because if it finds this address i try to use in the quick connect in the favorite hub it will use that credentials to login.

**Comment by pulsar-de** [comment]
> DC clients won't allow you to create two favorites with the same address.

I'am on your way, and it would be nice if this could be work in this way, but it's a clientside problem and we can't find a hubside solution at this place ;)

**Comment by Sopor** [comment]
I think you misunderstood me. That is why it should be possible to have more than one port and only ports that users can use will be visible when running `+hubinfo` (or other commands that will show the port number).
