### ISSUE TITLE
etc_alias.lua - create command alias

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#45]
A script that makes it possible to add command alias. So instead of writing `+usersearch` i only write `+us`. Or if you are an OP that have recently moved from [ADCH++](http://adchpp.sourceforge.net) to [Luadch](http://luadch.github.io/) and you have learn to use `+listreg` it would be easy to add that as an alias to `+usersearch` and all the OP's will be happy :)

**Comment by blasti** [comment]
will think about this

**Comment by perlaxe** [comment]
Perhaps not the most elegant, but I solved it by changing the scripts to add an alternate commands: like in case of useruptime for example, added cmd1. But of course this makes life more difficult when you want to upgrade to newer version.

local cmd = "useruptime"
local cmd1 = "uu"

...

    if (( command == cmd ) or ( command == cmd1 )) and param1 then
...

        assert( hubcmd.add( {cmd,cmd1}, onbmsg ) )

**Comment by blasti** [comment]
> Perhaps not the most elegant, but I solved it by changing the scripts to add an alternate commands: like in case of useruptime for example, added cmd1. But of course this makes life more difficult when you want to upgrade to newer version.
> 
> local cmd = "useruptime" local cmd1 = "uu"
> 
> ...
> 
> ```
> if (( command == cmd ) or ( command == cmd1 )) and param1 then
> ```
> 
> ...
> 
> ```
>     assert( hubcmd.add( {cmd,cmd1}, onbmsg ) )
> ```

Your approach is correct. Note, that if you use `hubcmd.add`, you don't have to check `( command == cmd )` in the registered function `onbmsg`. This is already checked by `hubcmd`:

https://github.com/luadch/luadch/blob/5c773e5de16110b4bc9d5244bb7fd6182dafc368/scripts/etc_hubcommands.lua#L49

So, to add aliases, basically do:

```lua
-- define commands and its aliases
local cmd = { "useruptime", "uu", "ut" }
-- add some menu entry for the first command
ucmd.add( ucmd_menu_ct1_2, cmd[1], { }, { "CT1" }, minlevel )
-- register commands
assert( hubcmd.add( cmd, onbmsg ) )
```

I added this for `usr_uptime.lua` in d06f9214bda2dac81e38ce8952f5026409bc813a

**Comment by Sopor** [comment]
I don't get it? Alias for one command and it is way to complex for us regular guys that don't code ☹

My suggestion was to create an alias script that was easy to edit and add and change alias for most of the commands you use in Luadch.

And when you update Luadch you have to edit every single script that you have added an alias to. Not very practical.

For this to work it must be very easy to add an alias.

You simple write `+alias add usersearch us` and `usersearch` now have a new alias called `us`.

To remove an alias you write `+alias remove usersearch us`.

**Comment by blasti** [comment]
Give me a complete list of aliases you think to be useful, and I'll officially add it.

But there are more important things to do then to write such a script.

**Comment by Sopor** [comment]
I asked for this for almost 5 years ago. No hurry, It can wait another 5 years.

There is no need to do it half way. Do it right or not at all.
