### ISSUE TITLE
cmd_reg.lua - comment won't be visible in OP_Chat

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#47]
When I register a user like this `+reg nick Elpidio 20 this is my brother` it will only show up like this in the OP_Chat: `<-HubSecurity> User  [-OP-]Loke  registered  Elpidio with level  20 [ REG ]`.
If i read in the cmd.log i will see this:
`Command: [+!#]reg nick Elpidio 20 this is my brother   |   used by: [-OP-]Loke`.
So the `comment` is missing from the OP_Chat and that can be a bit confusing. Did a really add it or did i do something wrong? I want all OP's to see when a commented is added.

**Comment by HypoM** [comment]
This is a possible solution to this, i can create a PR for it if @blasti thinks it is correct.

Replace line 324-333 with:
```lua
        else
            local message
            if desc ~= "" then
                message = utf_format( msg_report_comment, user_nick, target_firstnick, target_level, target_levelname, desc)
                description_add( target_firstnick, user_firstnick, desc )
            else
                message = utf_format( msg_report, user_nick, target_firstnick, target_level, target_levelname )
            end
            report.send( report_activate, report_hubbot, report_opchat, llevel, message )
            local message2 = utf_format( msg_ok, target_firstnick, password, target_level, target_levelname )
            user:reply( message2, hub_getbot )
            user:reply( utf_format( msg_accinfo, target_firstnick, password, target_level, target_levelname, hname, addy ), hub_getbot, hub_getbot )
        end
```
And alongside the other language-defintions at the top of cmd_reg.lua add this:
```LUA
local msg_report_comment = lang.msg_report_comment or "User  %s  registered  %s  with level  %d [ %s ], comment: %s"
```
And in cmd_reg.lang.en/cmd_reg.lang.de add:
```LUA
msg_report_comment = "User  %s  registered  %s  with level  %d [ %s ], comment: %s",
```

**Comment by blasti** [comment]
I think it would be better to make the comment default, and not optional. This simplifies the script, as well as the command and right click menus. The default value of the comment should be "" or "<NA>", and might be overwritten by the one who regs the user.

**Comment by Sopor** [comment]
It is still there ...

![image](https://user-images.githubusercontent.com/5789283/82951180-01656b00-9fa7-11ea-8d0f-b6ace6ed17a2.png)

**Comment by pulsar-de** [comment]
Done. now it shows the comment from the registered user as default if exists
