### ISSUE TITLE
cmd_usersearch.lua: Sort the output

### ISSUE THREAD

**Issue by HypoM** [luadch/luadch#53]
I think it would look better, and be easier to find a user in, if the output of the command was sorted on the content of `u.firstnick`.  
As it is now, it just seems to show up in the same order as it was written in the user-table (which i assume is always by reg-date).

**Comment by blasti** [comment]
I like the view by reg date. Maybe one can add an option to view alphabetically.

**Comment by HypoM** [comment]
I have to say i like that idea better, and will look into it later. In that case, i think it most likely is better to leave reg-date as the default sorting then (as people are most used to that by now).

**Comment by Sopor** [comment]
I don't believe they have a clue which order they are listed in and for me the alphabetically order is the most useful. The other order only looks like it was listed in random order. Only those with knowledge of the code knows it is listed by reg date.

**Comment by blasti** [comment]
I agree that if you don't see the reg date, it looks like being random. In that case it should be shown alphabetically.

**Comment by pulsar-de** [comment]
Now it shows the userlist in alphabetical order sorted by firstnick.
