### ISSUE TITLE
ptx_freshstuff_v0.8 (multi3) no rightclick menu

### ISSUE THREAD

**Issue by c0r4ir** [luadch/luadch#55]
OS: Ubuntu 16.04
Luadch v2.19
ptx_freshstuff_v0.8 

Right Click menu not appearing in client. I have not made any modifications to the .lua script. However, I am able to use freshstuff commands in the client.  What can be the issue?

**Comment by blasti** [comment]
This is the wrong place to open an issue for ptx_freshstuff, please goto [https://github.com/luadch/scripts/issues](https://github.com/luadch/scripts/issues).
Also please specify which client you are using, and whether you are hosting the hub by yourself.
