### ISSUE TITLE
Question! not an issue!

### ISSUE THREAD

**Issue by Ninja-FSE** [luadch/luadch#56]
I have ptx_freshstuff loaded and using Luadch Announcer Client. Working great!

But i have an question, how can i make so several users can use the same account on my hub and add new releases to ptx freshstuff? as it looks that the Client stays connected all the time.

Is there anyway to make the Announcer Client to connect to the hub, add the release and then disconnect?

**Comment by blasti** [comment]
each user should use its own announcer client. in any case: users should not share the same account in hub
