### ISSUE TITLE
Luadch doesn't really daemonize

### ISSUE THREAD

**Issue by seabert** [luadch/luadch#6]
I've been playing with luadch just for a few days, but I don't seem to be able to get the binary to fully daemonize. In other words I don't get my shell back after launching, even when using the -r flag (but not certain that is meant for that purpose).

My current workaround is to run luadch using the start-stop-daemon command as root:
`start-stop-daemon -u dcpp --exec /path/to/luadch/luadch -d /path/to/luadch -b -S`

**Comment by tarulas** [comment]
Would fix really help? systemd/daemontools/runit prefer it as is. start-stop-daemon works too.

**Comment by blasti** [comment]
Hi seabert,
you can use

./luadch &

to get your shell back.

**Comment by seabert** [comment]
@blasti sure, but when you run it like that and then logout of the shell, the program will be killed.

My issue is that for a user that has a shell without root all the things that @tarulas mentioned won't work. Even more, running luadch through these kind of tools (via root) is hackish imho.

**Comment by blasti** [comment]
I see. So if you want your shell back, and want luadch to run without root and beyond logout, maybe it helps to just use screen or tmux?

I agree that this would be a nice feature. But as far as I understand it, adding this feature would be non-trivial, expecially if we also want it to work on windows. There are some other things I want and need to do first.

**Comment by Sopor** [comment]
I use `tmux`

**Comment by Sopor** [comment]
I have been running Luadch as a service in Windows by using [NSSM](https://nssm.cc) and it seems to work.

**Comment by blasti** [comment]
@seabert: Latest Luadch (5e64e35) supports daemonization on unix. Use

```
luadch -d
```

to run it as a daemon. To terminate it, you can use

```
pkill -SIGTERM luadch
```

**Comment by Sopor** [comment]
I did run it as `luadch -d` but it will still not leave the shell back or this isn't working in Luadch 2.21?

**Comment by blasti** [comment]
> I did run it as `luadch -d` but it will still not leave the shell back or this isn't working in Luadch 2.21?

Correct, this is a feature of Luadch 2.22, see

https://github.com/luadch/luadch/blob/80e78e8931f75e7a976a65139a6b458e89166045/docs/CHANGELOG#L72

 But you can use it today by compiling the latest source.
