### ISSUE TITLE
make it possible to hide INF fields from users

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#60]
It would be nice if it was possible to hide INF from the users. At least Description and Email where users can type his own text. Some users even type their passwords in the description. OP's should of course always see it.

**Comment by blasti** [comment]
there are scripts which are already doing this to some extend. see for instance
[https://github.com/luadch/luadch/blob/master/scripts/hub_inf_manager.lua](https://github.com/luadch/luadch/blob/master/scripts/hub_inf_manager.lua) 
[https://github.com/luadch/luadch/blob/master/scripts/usr_desc_prefix.lua](https://github.com/luadch/luadch/blob/master/scripts/usr_desc_prefix.lua)
[https://github.com/luadch/luadch/blob/master/scripts/usr_hide_share.lua](https://github.com/luadch/luadch/blob/master/scripts/usr_hide_share.lua)

**Comment by Sopor** [comment]
One script will: `this script kills users with forbidden inf flags` and the desc script is not working very well. I have already reported that to pulsar. These script is not was i was asking for.

**Comment by blasti** [comment]
yes but those scripts can be easily customized to strip the description/email. just register an "onInf" event and delete the "DE" an "EM" flags
