### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by Havokdan** [luadch/luadch#61]
Good morning, I'm a beginner, after a lot of trouble, I managed to put a hub here to test it, however I would like to know how I add the rules, nor are the rules, but rather how I configure the rules text to display in the hub, could anyone help me?

**Comment by blasti** [comment]
You need to edit the file [https://github.com/luadch/luadch/blob/master/scripts/cmd_rules.lua](https://github.com/luadch/luadch/blob/master/scripts/cmd_rules.lua#L65). Write your message into the variable [msg_rules](https://github.com/luadch/luadch/blob/master/scripts/cmd_rules.lua#L65).

**Comment by Sopor** [comment]
You need to write the message in [cmd_rules.lang.en](https://github.com/luadch/luadch/blob/master/scripts/lang/cmd_rules.lang.en#L13) or `cmd_rules.lang.de` depending on what language you are using.

**Comment by Havokdan** [comment]
Thank you, I already understand, I have done the translations for my language and I posted in the "issues" section of the translation section.
