### ISSUE TITLE
Limit the amount of chars to show from each post

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#62]
When a user login it is possible to set how many posts to show from main history, but there should also be a settings to limit the amount of chars in every post. A post can be 1 char but it can also be 5000 chars or even more. Therefore a settings to cut very long posts would be great.

**Comment by pulsar-de** [comment]
That really makes sense. Thx.

**Comment by blasti** [comment]
Wrong approach.

Don't accept mainchat messages with length > limit in the first place. Then such messages won't be saved in the chatlog.
And what is definitely the wrong thing to do is to cut a text in some arbitrary way. Either keep a text as it is, or discard it completely.

**Comment by pulsar-de** [comment]
I removed the "max_characters" functionality with "string.sub" from code.

**Comment by Sopor** [comment]
Any fix for this yet?
