### ISSUE TITLE
Traffic manager - Users that are blocked from downloading shouldn't receive searches

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#63]
When a user is blocked the client will still answer on incoming searches and this will make my client add this user to my queue but because the user is blocked it will never download anything from this user. So after a while i will have a lot of partial file lists in queue that never will go away until i manually remove them.

So when a user is blocked it should also block incoming searches so the user won't answer on search matches.

**Comment by pulsar-de** [comment]
fixed with: https://github.com/luadch/luadch/commit/213d96c298dbd5bab084c779e1281dcc0f5f9363
