### ISSUE TITLE
cmd_usersearch.lua

### ISSUE THREAD

**Issue by Ninja-FSE** [luadch/luadch#65]
When im doing a usersearch the scripts returns with wrong "Last seen" time. This doesnt happen to all users only to a few. Is there anyway to restet the DB?

Or does it have something todo with https://github.com/luadch/luadch/issues/58 ?

**Comment by Sopor** [comment]
How do you know the `Last seen` is wrong?

**Comment by Ninja-FSE** [comment]
I tested it with a user who left the hub, and got "Last seen: 19 days, 20 hours, 42 minutes and 47 seconds ago" right after he left

**Comment by Sopor** [comment]
And if you check the same user again it will still show the same time?

**Comment by Ninja-FSE** [comment]
yes, but i think i fixed it, i updated cmd_usersearch and usr_uptime.lua witht the new versions

**Comment by Sopor** [comment]
I haven't seen any issues with the `Last seen` before, but i can confess that i don't use that command very often on recently logged out users :)

**Comment by Sopor** [comment]
@apax0r If this is solved you maybe should close it?

**Comment by Ninja-FSE** [comment]
@Sopor-  No i did not :(

**Comment by pulsar-de** [comment]
Should fixed.
