### ISSUE TITLE
script error: ././scripts/hub_runtime.lua:122

### ISSUE THREAD

**Issue by Hakker** [luadch/luadch#67]
<[BOT]HubSecurity> scripts.lua: script error: ././scripts/hub_runtime.lua:122: attempt to index upvalue 'hci_tbl' (a nil value) (listener: onTimer; script: 'hub_runtime.lua')

It keeps spamming that every second. running it on Windows 10 machine.

**Comment by Sopor** [comment]
Do a +reload and if that doesn't help, try +restart...
Have you been doing something in the `hci.lua`? Check the file so it is UTF-8 without BOM and not corrupt. If so, replace with a new one.

**Comment by Hakker** [comment]
Have done nothing in the hci.lua and a reload or restart only solves it for 5 minutes.

**Comment by Sopor** [comment]
Have you replaced the `hci.lua` with the original hci.lua from `luadch-2.19-win-x86_64.zip`?

**Comment by Hakker** [comment]
yes. and even went as far as reinstalling everything and it still does it.

**Comment by Sopor** [comment]
Where have you installed Luadch (path)?

**Comment by Hakker** [comment]
c:\luadch not in any windows special dirs if that's what you think. Running it as administrator doesn't solve anything either.

**Comment by pulsar-de** [comment]
This happens with a faulty hci.lua. I will write a control function to prevent this in the future.
