### ISSUE TITLE
delregging a user will not remove the user from banned users

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#69]
If i have a user banned and i change my mind so instead i choose to delreg the user, the user will still be banned. It is possible to manually unban the user but if i delreg a user it should remove the ban too.

**Comment by pulsar-de** [comment]
- update: "scripts/cmd_delreg.lua"
    - fix issue: https://github.com/luadch/luadch/issues/69
        - remove delregged user from bans if exists  / thx Sopor

- update: "scripts/cmd_ban.lua"
    - add "del()" function to export unban functionality in other scripts

Should be fixed now.

Greets
