### ISSUE TITLE
Luasec doesn't work out of the box (on Debian 64-bit)

### ISSUE THREAD

**Issue by seabert** [luadch/luadch#7]
I tried using luadch as the precompiled Debian build and also as compiled from source. With both ways luasec doesn't work. In the end I resolved this by installing the lua-sec packages and symlink the files to the luadch directory.

```
$ ls -l luadch/lib/luasec/*
luadch/lib/luasec/lua:
total 0
lrwxrwxrwx 1 dcpp dcpp 34 Mar  3 08:55 options.lua -> /usr/share/lua/5.2/ssl/options.lua
lrwxrwxrwx 1 dcpp dcpp 26 Mar  3 08:55 ssl.lua -> /usr/share/lua/5.2/ssl.lua

luadch/lib/luasec/ssl:
total 0
lrwxrwxrwx 1 dcpp dcpp 40 Mar  3 08:55 ssl.so -> /usr/lib/x86_64-linux-gnu/lua/5.1/ssl.so
```

**Comment by blasti** [comment]
Hi seabert,
luasec should work now if you compile luadch from source.
I merged tarulas fix.
