### ISSUE TITLE
detect users that have disabled the encryption?

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#70]
Is it possible to detect if the users have disabled the encryption when they connect and in that case not letting them connect? It would be nice if it could detect users that not use the keyprint.

**Comment by blasti** [comment]
If a user sends a INF without KP flag, no keyprint is used. That can of course be detected.

Otherwise, if your hub has only adcs ports, the users have no other choice than using encryption.

**Comment by Sopor** [comment]
It is still possible to disable encryption for file transfers. I assume that was what i meant, but it was almost 2 years ago i wrote this :)

Both DC++ and AirDC++ can disable file transfer encryption.

How about keyprint?

**Comment by blasti** [comment]
> Both DC++ and AirDC++ can disable file transfer encryption.

I don't think it is possible to prevent this from hub side.
