### ISSUE TITLE
TLSv1_2 error @compile

### ISSUE THREAD

**Issue by bashinator** [luadch/luadch#71]
Hey ::

context.c: In function ‘str2method’:
context.c:100:3: warning: ‘TLSv1_method’ is deprecated [-Wdeprecated-declarations]
   if (!strcmp(method, "tlsv1"))   return TLSv1_method();
   ^~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from context.c:16:
/usr/include/openssl/ssl.h:1624:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
context.c:102:3: warning: ‘TLSv1_1_method’ is deprecated [-Wdeprecated-declarations]
   if (!strcmp(method, "tlsv1_1")) return TLSv1_1_method();
   ^~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from context.c:16:
/usr/include/openssl/ssl.h:1630:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
 ^
context.c:103:3: warning: ‘TLSv1_2_method’ is deprecated [-Wdeprecated-declarations]
   if (!strcmp(method, "tlsv1_2")) return TLSv1_2_method();
   ^~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from context.c:16:
/usr/include/openssl/ssl.h:1636:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
 ^
context.c: In function ‘set_curve’:
context.c:562:8: warning: unused variable ‘ret’ [-Wunused-variable]
   long ret;
        ^~~

on Debain Stretch // openssl 1.1.0f

tried OpenSSL 1.1.0g  2 Nov 2017

and Openssl 1.1.1 (newsted)

everytime that mistakes, @ compile.. dunno why

**Comment by blasti** [comment]
This is a warning, not an error. The luasec module seems to use deprecated OpenSSL methods.
This will probably be fixed by the luasec maintainers in future releases.
