### ISSUE TITLE
Make it possible to hide bots/users/chat room/etc

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#73]
Make it possible to hide `OP_Chat` by level. This will prevent confusing the users. I can't see any reason why chat rooms for level 60+ should be visible for lower levels?

**Comment by Ninja-FSE** [comment]
Any updates on this? Whould be a nice future to have

**Comment by Ninja-FSE** [comment]
Sorry for bumping an old issue that is closed and seems to be fixed, but this fix only apply's to Op-Chat, how does this work if i want to hide other bots or users?

**Comment by blasti** [comment]
Same way as here:

https://github.com/luadch/luadch/blob/d7135a01ac78439508e26355471c1219004d0cd0/scripts/etc_hide_opchat.lua#L20

Get the SID of a user/bot you want to hide, then send QUI message to target user.
What users/bots do you want to hide?

**Comment by Sopor** [comment]
It seems that if i do a `+reload` the op_chat wil be visible again :(

**Comment by blasti** [comment]
Of course. Easy fix: Register onStart listener, iterate through all  online users, test for level, send Quit message.
