### ISSUE TITLE
Set redirect on min share/slots,mas share,hubs etc

### ISSUE THREAD

**Issue by HadesDCH** [luadch/luadch#74]
I'm trying to get LUADCH to redirect users instead of just disconnect when min share/max share min/max slots are not met.
Looks like there is only manual redir command fos specific profiles. Can this be done ? Am i miising something in configs?
Thanx!

**Comment by pulsar-de** [comment]
Fixed. to use these changes you have to update the following files:

- [core/hub.lua](https://github.com/luadch/luadch/blob/master/core/hub.lua)
- [core/cfg.lua](https://github.com/luadch/luadch/blob/master/core/cfg.lua)
- [cfg/cfg.tbl](https://github.com/luadch/luadch/blob/master/examples/cfg/cfg.tbl) (usr_share.lua settings, usr_slots.lua settings)
- [scripts/usr_share.lua](https://github.com/luadch/luadch/blob/master/scripts/usr_share.lua) + lang files
- [scripts/usr_slots.lua](https://github.com/luadch/luadch/blob/master/scripts/usr_share.lua) + lang files

**Comment by ManelGT1956** [comment]
@pulsar-de , link to usr_share.lua is same as usr_slots.lua (same link twice, also used to the last script...), we only get to the only and first one, didn't get to intended second script... could you check it and correct link or something?...
Or else/also, a simple explanation for noobs/newbies as to where and how to edit it to our needs, maybe...?
Thanks in advance...

**Comment by ManelGT1956** [comment]
Or maybe a short explanation to noobs and newbies, as to what chnge in the script to meet our needs... ;)
Thanks...

**Comment by ManelGT1956** [comment]
*...change...
