### ISSUE TITLE
Debian build is compiled for 32-bit, need extra libs on 64-bit machines

### ISSUE THREAD

**Issue by seabert** [luadch/luadch#8]
For the Debian build of luadch, one need extra libs on 64-bit only machines. I'm not certain which ones exactly, but at least `lib32stdc++6` and probably others. This should at least be documented, _or_ the build should be made 64-bit, since most modern installs are 64-bit anyway.

**Comment by blasti** [comment]
Hi seabert,
I recommend to compile luadch on Linux from source by using the "compile_with_gcc.sh" shell script.
For instance on my Debian 64-bit system I only had to "apt-get install libssl-dev", which installs the development stuff of openssl, and after that the compilation
went through without issues.
