### ISSUE TITLE
usr_uptime.lua:175: attempt to index field '?' (a nil value) (listener: onLogout; script: 'usr_uptime.lua')

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#81]
The new usr_uptime.lua will sometimes show this message
```
scripts.lua: script error: ././scripts/usr_uptime.lua:175: attempt to index field '?' (a nil value) (listener: onLogout; script: 'usr_uptime.lua')
```
and it seems to happen when users get the message
```
An existing connection was forcibly closed by the remote host
```
and if you have joins and parts enabled in your client you can see they disconnect and reconnect the exact same time or 1-2 second later. This seems to generate this error message.

**Comment by HadesDCH** [comment]
When hub is  shut down (without  ctrl+c) for example on system crash or just reboot, this issue appears to be very common. Its related to missing or corrupted file usr_uptime.tbl located in data folder.
This triggers mass flood of all OPS PMs with the error message (bigger the hub - bigger the flood).
How is storing this in database instead - maybe more reliable?

**Comment by pulsar-de** [comment]
update: "scripts/usr_uptime.lua"
- reduce timer to 1 minute
- fix: https://github.com/luadch/luadch/issues/81
    - add "opchat.feed()" function to report corrupt or missing database file
- changes: "scripts/lang/usr_uptime.lang.de"
- changes: "scripts/lang/usr_uptime.lang.en"

Should be fixed now.
