### ISSUE TITLE
hide IP address in user list?

### ISSUE THREAD

**Issue by luadchuser** [luadch/luadch#85]
This might be a stupid question, but is there a way to hide IP addresses in the user list? It's certainly possible in other hubs, I've seen it before. (I know that the clients of course will eventually need the IP address of another client from the hub to download, but it would be nice to hide them in the user list).
Thanks!

**Comment by blasti** [comment]
1. You cannot hide the IP adress without breaking up/download capability.
2. Also, the client software decides what it will show to the user in the userlist.

**Comment by Sopor** [comment]
Other hubsoft can do it, so why not Luadch, but maybe that was the old NMDC?

**Comment by blasti** [comment]
> Other hubsoft can do it, so why not Luadch, but maybe that was the old NMDC?

In theory it is possible to "hide" the IP, by not sending I4 and I6 flags in the INF. Then the question is, what happens if somebody wants to download something.  One has to test this, probably resend INFs with IPs, etc. I won't spend time on this looming clusterfuck, as the benefit is... zero.
