### ISSUE TITLE
Connecting to non SSL port does not fully establish connection

### ISSUE THREAD

**Issue by AlienXAXS** [luadch/luadch#87]
Hi,
I am a new luadch user, and maybe just need some configuration help.

I am attempting to use luadch to allow users to connect to my hub simply by entering the address in Quick Connect for example, so I've set the property 'tcp_ports' to 411.

However, trying to use both DC++ and AirDC++ (both latest versions) causes the client to connect to the hub, but nothing else happens.  I get no chat, user list or anything - it just sits there.

Attempting to connect to adc://ip:port throws the error 'The requested address is not valid in its context.' in both AirDC and DC++ clients.

Just hoping that I can get some assistance, or some explanation of how this should work in this type of setup.

my Luadch install works fine with ADCS, and is configured to use SSL as such.

Thank you.

**Comment by Sopor** [comment]
It should not be any problems to get it to run. You need to check everything again so you don't have any firewall or port that you need to be open in your router. You should also try another port.
Did you try to connect to your own hub? Try adc://127.0.0.1:411 and see if that works.

**Comment by AlienXAXS** [comment]
After doing some more research, i assume that Luadch doesnt support NMDC (or something like that?)

But i also realise that i need to define the port on the ADC URL, i assumed it used 411 by default.
