### ISSUE TITLE
Running luadch on Windows XP

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#94]
Got some errors.

Config is default.

![Screenshot_1](https://user-images.githubusercontent.com/50278147/81023724-f886eb00-8e79-11ea-8dc7-52000a7f7c38.png)

**Comment by blasti** [comment]
1. Always post error messages in **english.**
2. Always post the luadch **version** you are using, or whether you compiled it by yourself.
3. WinXP is end of life since at least 2015. Why should we support a dead operating system?

**Comment by Tantrix** [comment]
1) 'cfg' "wmic" is not a program
2) 2.21 downloaded, not compiled
3) The website says 'luadch was successfully tested on Windows XP'.

**Comment by blasti** [comment]
> The website says 'luadch was successfully tested on Windows XP'.

Yes, 10 years ago.
