### ISSUE TITLE
Deleting users gives an error

### ISSUE THREAD

**Issue by Ninja-FSE** [luadch/luadch#98]
When im trying to delete a user i get this error msg

`[2020-05-13 | 16:27:38] scripts.lua: script error: ././scripts/cmd_delreg.lua:271: attempt to read undeclared var: 'ban' (listener: onBroadcast; script: 'etc_hubcommands.lua')
`

`[18:58:32] <Hubbot> [command] +delreg nick User`
`[18:58:32] <Hubbot> Unknown command`

Running latest version, Luadch v2.22 RC3

Edit:

The user is getting deleted from user.tbl file.

**Comment by blasti** [comment]
Bug was introduced here:

https://github.com/luadch/luadch/commit/01a109df9614949f7250dd51cf7d1bda4c589061#diff-87368ac073d4b8f17b4c2e5358af2a44
